### ISSUE TITLE
socket timeout! connection closed !!!!

### ISSUE THREAD

**Issue by preetusha** [mkozjak/node-telnet-client#100]
Hello,
my code looks as follow 

![image](https://user-images.githubusercontent.com/14831381/33674672-2a20b900-da7e-11e7-97e1-e13ec00b4c47.png)

shellprompt when i telnet looks like:

![image](https://user-images.githubusercontent.com/14831381/33674776-7f5c808e-da7e-11e7-8b51-fcd87572b53b.png)

i get the session timeout everytime, where am i going wrong!! new to this , need help
Thanks in advance :)

**Comment by mkozjak** [comment]
Hello. Your code looks okay to me. What type of telnet server is this? Can you provide me with the tcpdump?

**Comment by preetusha** [comment]
its a cisco switch

**Comment by preetusha** [comment]
with ip 192.168.100.200

**Comment by preetusha** [comment]
what excatly do you mean by tcpdump?

**Comment by mkozjak** [comment]
tcpdump is a network capture of data with an application such as Wireshark.

**Comment by preetusha** [comment]
since its a cisco switch , asa i know it doesnt capture data, how do i get the tcp dump from the switch? any command in specific?? thanks :)

**Comment by mkozjak** [comment]
Do a capture from your pc, not from the switch. On Windows.

**Comment by mkozjak** [comment]
@fanlyze You get a timeout when logging in or when receiving a normal command response?

**Comment by fanlyze** [comment]
tcpdump

[telc.zip](https://github.com/mkozjak/node-telnet-client/files/1942252/telc.zip)

**Comment by fanlyze** [comment]
![image](https://user-images.githubusercontent.com/35338391/39229234-724fd63c-4894-11e8-8c17-d50ee780b020.png)

**Comment by mkozjak** [comment]
@fanlyze What happens if you try a non-regex loginPrompt, like "login: "?

**Comment by fanlyze** [comment]
@mkozjak you mean " loginPrompt: 'login: ',"?

**Comment by mkozjak** [comment]
yes

**Comment by manuGallegos** [comment]
Excuse me for interrupting. I'm trying to connect to a telnet server on windows, but it always comes out timeout. this is my code:
``
var Telnet = require('telnet-client')
var connection = new Telnet()

var params = {
	host: '192.168.1.180',
	port: 23,
	shellPrompt: '/^.*#$/i',
	loginPrompt: '/username[: ]*$/i',
	passwordPrompt: '/password[: ]*$/i',
	username: 'admin',
	password: 'Bps2018',
	initialLFCR: true,
	timeout: 10000
	// removeEcho: 4
}

connection.on('data', function(data) {
	console.log(data)
});

connection.on('connect', function() {
	console.log('conection ok')
})

connection.on('failedlogin',function(msg) {
    console.log("Login failed !",msg)
})

connection.on('ready', function(prompt) {
	console.log("ok") // this never appears
	connection.exec(cmd, function(err, response) {
		console.log(response)
	})
})

connection.on('timeout', function() {
	console.log('socket timeout!')
	connection.end()
})

connection.on('close', function() {
	console.log('connection closed')
})

connection.connect(params)
``

can you help me please????

**Comment by mkozjak** [comment]
@manuGallegos PR would be really welcome!!
