### ISSUE TITLE
What am I doing wrong?

### ISSUE THREAD

**Issue by alexwbai** [mkozjak/node-telnet-client#101]
Hey likely a dumb problem I have here but all I'm looking to do is telnet to a switch and run one tftp command and quit.  That's it.  This is my code:

```
const Telnet = require('telnet-client')

async function westellRun() {
  let connection = new Telnet()

  let params = {
    host: '10.0.0.91',
    port: 23,
    //shellPrompt: '#',
    timeout: 4500,
    username: 'admin',
    password: 'password',
    loginPrompt: 'login:',
    passwordPrompt: 'Password:'
  }

    await connection.connect(params)

  let res = await connection.exec("copy startup-config tftp://10.0.0.49/westells/alextest600")
  
    console.log('async result:', res);

}

westellRun().catch((err) => {
    console.log(err)
})
```

What happens here is that it appears to connect but I get a timeout error like this:

> Alexanders-MacBook-Pro:switch_backup_node awitte$ node westell3.js
> Error: response not received
>     at Timeout.setTimeout [as _onTimeout] (/Users/awitte/Documents/GitHub/switch_backup_node/node_modules/telnet-client/lib/index.js:150:47)
>     at ontimeout (timers.js:488:11)
>     at tryOnTimeout (timers.js:323:5)
>     at Timer.listOnTimeout (timers.js:283:5)

I have to CTRL C to quit it.  If I run a different command instead of the the tftp one (like a "show version") I get the correct output although I still need to CTRL C to end the process.  That tftp command works fine if I manually telnet in and executes in about a second.  Any thoughts?

**Comment by mkozjak** [comment]
Hello, @alexwbai. You will need a `shellPrompt` enabled and set correctly, either way. If you manually connect with telnet, you'll see you get some kind of a shell.

**Comment by alexwbai** [comment]
Regardless if I set a shellPrompt, I am able to successfully connect to the switch.  The weird thing is if I run one command (eg. show users) the output is fine.  If I run another command (copy startup-config tftp://10.0.0.49/westells/alextest600) I get a timeout error.  Both commands work fine when I manually connect to the switch. Same results with and without a shellPrompt set.  Just curious if you've seen this kind of behaviour before.

**Comment by alexwbai** [comment]
Also even when it outputs the correct output (e.g. after a "show users" command) it just hangs and I need to force quit.

**Comment by mkozjak** [comment]
Are you sure 4 and a half seconds are enough for the transfer to end and tftp to return?

**Comment by alexwbai** [comment]
That timeout value is not recognized after I have logged into the device.  (the "timeout" error response is immediate).  Check it out:

CODE:
```
const Telnet = require('telnet-client')

async function westellRun() {
  let connection = new Telnet();

  let params = {
    host: '10.0.0.91',
    port: 23,
    shellPrompt: 'weos#',
    timeout: 1000000,
    username: 'admin',
    password: 'password',
    //loginPrompt: 'Operations_lab login:',
    passwordPrompt: 'Password:'
  }

    await connection.connect(params);

   //let res = await connection.exec("show users");
    let res = await connection.exec('copy startup-config tftp://10.0.0.49/westells/alextest600');
    //let res2 = await connection.exec("exit");
    //let res3 = await connection.exec("show udp connections");
    console.log('async result:', res);

}
console.log("I am going to run!!!!");

westellRun().catch((err) => {
    console.log("Error!",err);
})
```
RESULT:

> Alexanders-MacBook-Pro:switch_backup_node awitte$ node westell3.js
> I am going to run!!!!
> Error! Error: response not received
>     at Timeout.setTimeout [as _onTimeout] (/Users/awitte/Documents/GitHub/switch_backup_node/node_modules/telnet-client/lib/index.js:150:47)
>     at ontimeout (timers.js:478:11)
>     at tryOnTimeout (timers.js:302:5)
>     at Timer.listOnTimeout (timers.js:262:5)


CODE (with another exec statement):
```
const Telnet = require('telnet-client')

async function westellRun() {
  let connection = new Telnet();

  let params = {
    host: '10.0.0.91',
    port: 23,
    shellPrompt: 'weos#',
    timeout: 1000000,
    username: 'admin',
    password: 'password',
    //loginPrompt: 'Operations_lab login:',
    passwordPrompt: 'Password:'
  }

    await connection.connect(params);

   let res = await connection.exec("show users");
    //let res = await connection.exec('copy startup-config tftp://10.0.0.49/westells/alextest600');
    //let res2 = await connection.exec("exit");
    //let res3 = await connection.exec("show udp connections");
    console.log('async result:', res);

}
console.log("I am going to run!!!!");

westellRun().catch((err) => {
    console.log("Error!",err);
})

This error result is immediate and does not wait the specified timeout duration. 
```
RESULT:

> Alexanders-MacBook-Pro:switch_backup_node awitte$ node westell3.js
> I am going to run!!!!
> async result: 
> Id  Mode  			User	Peer-Address
> 
>  3 telnet  	               admin	10.0.5.210


So I am able to connect to the device and one command successfully gives me a result and the other returns an error although the command is successful when I manually run it (and completes in a second).  In both instances the prompt is not returned to me- (likely I need to add a "close connection" statement somewhere...?)

**Comment by mkozjak** [comment]
The switch is not returning the prompt after commands are finished?
Try using `.send` instead: https://github.com/mkozjak/node-telnet-client/blob/167523f9d86a5a5dfda2694006ee3bcfd9720276/test/004_negotiation_optional.js#L37

**Comment by alexwbai** [comment]
Hey mkozjak thanks for helping out.  `.send` is giving me unreadable characters in the response.  Anyway I managed to do this another way so I'm good.  You can go ahead and close this.  Thanks!
