### ISSUE TITLE
loginPrompt and failedLoginMatch are same

### ISSUE THREAD

**Issue by RomanDoroshenko** [mkozjak/node-telnet-client#105]
Say, I have a device that for incorrect credentials just sends another prompt without any error patterns.
Somehow I need to disable failedLoginMatch pattern for initial prompt and put it back just before authentication to catch second loginPrompt as failedLoginMatch pattern. Thx for help in advance!

**Comment by RomanDoroshenko** [comment]
Resolved with failedLoginMatch = null

**Comment by mkozjak** [comment]
Thanks for informing!
