### ISSUE TITLE
Option Negotiation Issues

### ISSUE THREAD

**Issue by jfosnight** [mkozjak/node-telnet-client#106]
I'm not really sure if this a bug so much in your client, or in the device that I'm trying to telnet into.

After much troubleshooting, I discovered that the telnet host is sending option negotiation in two separate packets.  The first packet contains only `ff` and the next packet contains the rest of the option negotiation data `fb 03 ff fd 18 ff fb 01 ff fd 1f ff fd 21`.  (In wireshark the first packet is flagged as being a "Malformed Packet").

In order to get around the client script not handling this correctly, I just added a simple check to make sure that the next byte of data is set before doing option negotiation.  However, this means that the client is not doing any option negotiation at all.  It does still work, but I don't know what kind of impact this would have on the client.

Here is the code that I changed `if (chunk[0] === 255 && chunk[1] !== 255) {` becomes this `if (chunk[0] === 255 && typeof chunk[1] !== 'undefined' && chunk[1] !== 255) {`

I didn't know if the TELNET specs defined whether option negotiation needed to all be sent in a single packet or if it could be split between multiple packets?  The telnet server does the same thing when using PuTTY to login.  My guess is that the telnet server just isn't implemented correctly, in which case, it would be nice if the script would fail more gracefully.

[Telnet Packet Captures.zip](https://github.com/mkozjak/node-telnet-client/files/1744977/Telnet.Packet.Captures.zip)

Thanks for a great module!  I've used this client to log into a couple other types of devices and it's worked great (though it is a bit hard to debug issues at times).

**Comment by mkozjak** [comment]
@jfosnight Hi! Thank you for using this library! Yes, the debugging is not great with this library. I've been having plans to make it easier to debug, though #41 

Can you please check if the library works with your other devices once you make that change? Does `npm install && npm test` pass?

**Comment by jfosnight** [comment]
Hey sorry, I forgot to respond.  Yes the other devices worked fine with the change that I made.  I did not get a chance to run `npm install` or `npm test`

**Comment by mkozjak** [comment]
Ok, please inform me if you do so!

**Comment by mkozjak** [comment]
Stale, I guess.
