### ISSUE TITLE
Prompt detection unreliable

### ISSUE THREAD

**Issue by silverwind** [mkozjak/node-telnet-client#11]
When a prompt string arrives split up in multiple chunks, detection likely fails. I have worked around it for now with [this](https://github.com/silverwind/node-telnet-client/blob/40648cd71f55dcb9a3a14b9b029958b9388f9ad9/lib/telnet-client.js#L55-L64) which accumulates chunks and parses them only after 50ms of inactivity, but it's beyond ugly, and I think there're likely more elegant solutions to this problem.

**Comment by aicioara** [comment]
Found this to be helpful https://github.com/mkozjak/node-telnet-client/issues/117
