### ISSUE TITLE
Attempting to login to rcon server, getting error.

### ISSUE THREAD

**Issue by encloinc** [mkozjak/node-telnet-client#110]
```
var Telnet = require('telnet-client')
var connection = new Telnet()

var params = {
  host: 'anip',
  port: 27115,
  shellPrompt: 'login apassword',
  password: 'apassword',
  timeout: 1500,
  // removeEcho: 4
}

connection.on("data", function(data){
    console.log(''+data);
});

connection.on('ready', function(prompt) {
  connection.exec(cmd, function(err, response) {
    console.log(response)
  })
})

connection.on('timeout', function() {
  console.log('socket timeout!')
  connection.end()
})

connection.on('close', function() {
  console.log('connection closed')
})

connection.connect(params)
```

I'm trying to login to an rcon server based on RocketMod, however everytime i login i get the socket timeout! and then the connection closed. I've checked the ip, port, and password fields multiple times. All i want to be able to do is to login to the rcon server (Which is done with the command "login (password)") and then just be able to send the rcon server commands and receive the response from those commands or from things happening in the background. How would I do this?

**Comment by mkozjak** [comment]
@encloinc Is there a possibility to make me a testing account at your server so I can try this?

**Comment by mkozjak** [comment]
Try with an option `negotiationMandatory`.
