### ISSUE TITLE
reboot modem

### ISSUE THREAD

**Issue by reznikGit** [mkozjak/node-telnet-client#111]
> async function modemReboot() {
>     const connection = new Telnet();
>     const params = {
>         host: "192.168.8.1",
>         port: 23,
>         shellPrompt: "/ # ",
>         timeout: 1000
>     };
> 
>     await connection.connect(params);
>     await connection.exec("reboot").catch(_.noop);
>     await connection.destroy();
> }

Hi, i want connect to my modem e3370, and reboot it.
On my pc - this code work good, but in my notebook i have error.

> events.js:167
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: read ECONNRESET
>     at TCP.onread (net.js:659:25)
> Emitted 'error' event at:
>     at Socket.socket.on.error (D:\modem\node_modules\telnet-client\lib\index.js:129:22)
>     at Socket.emit (events.js:182:13)
>     at emitErrorNT (internal/streams/destroy.js:82:8)
>     at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
>     at process._tickCallback (internal/process/next_tick.js:63:19)

Say me pls, how i can fix it. Add try/catch - not work

**Comment by mkozjak** [comment]
Hi!

`ECONNRESET` means the server side abruptly closed the connection for some reason (maybe protocol errors). Can you check logs on your router, maybe?

Also, `shellPrompt` should be set to a proper value. This one is probably not correct for your setup.

**Comment by reznikGit** [comment]
What i must insert in shellPrompt ? I want send command in my modem by telnet and exit at this moment(at once), what i must do? You say 

> server side abruptly closed the connection

You are right after exec command reboot modem close connection at once.
How to fix it? What i must do?

**Comment by mkozjak** [comment]
You can connect to your modem via telnet from linux or windows and see what is the command prompt like (the hashtag or whatever before the command you're inputting).

**Comment by reznikGit** [comment]
Hi, you think problem in inncorect shellPrompt? What happened if i delete this field?
for example
const params = {host: "192.168.8.1"};

**Comment by mkozjak** [comment]
Yes, the problem might be in a wrong shellPrompt. It will not work if you unset that option.

**Comment by reznikGit** [comment]
> root@android:/ #

**Comment by reznikGit** [comment]
in my console (putty) on pc and notebook

**Comment by reznikGit** [comment]
problem is not in shellPrompt

**Comment by mkozjak** [comment]
Paste me your entire code, please!

**Comment by reznikGit** [comment]
"use strict";

const fs = require("fs");
const _ = require("lodash");
const Telnet = require("telnet-client");
const { execSync } = require("child_process");
const internetAvailable = require("internet-available");

const { mails } = require("./mails.json");
const exp = "ams";

function delay(minutes) {
    return new Promise(resolve => setTimeout(resolve, minutes * 60 * 1000));
}

async function modemReboot() {
    const connection = new Telnet();
    const params = { host: "192.168.8.1" };

    await connection.connect(params);
    await connection.exec("reboot").catch(_.noop);
    await connection.destroy();
}

async function runActions(visits, reg) {
    const path = `${__dirname}\\action\\`;
    const arr = _.shuffle([
        ..._.fill(new Array(visits - reg), "visits"),
        ..._.fill(new Array(reg), "reg")
    ]);
    for (let item of arr) {
        let file = `${path}${item}.${exp}`;
        if (item === "reg") {
            const data = mails.pop();
            if (data) {
                file = `${path}${item}-tmp.${exp}`;
                fs.writeFileSync(
                    file,
                    _.template(
                        fs.readFileSync(`${path}${item}.${exp}`).toString()
                    )(data)
                );
            }
        }
        await modemReboot();
        await internetAvailable({ timeout: 10000, retries: 20 });
        // execSync(file);
        await delay(_.random(1, 5));
    }
}

runActions(180, 16);

**Comment by mkozjak** [comment]
You didn't set `shellPrompt` in `const params = { host: "192.168.8.1" };` to `/ #`

**Comment by reznikGit** [comment]
I wrote above that adding shellPrompt: "/ #" does not lead to anything.
I still have the same mistake, I'll look for other solutions then, but thanks anyway

**Comment by mkozjak** [comment]
@reznikGit Do you realize that there was a `/ # ` in your first example and not `/ #`? If yes, then there's nothing more I can do. Cheers.

**Comment by reznikGit** [comment]
Hi, u mean `/ #` without space after #? ok i try it

**Comment by reznikGit** [comment]
Can you change https://github.com/mkozjak/node-telnet-client/blob/06bf78b341715bfbc04a92f511be10144d8c62c3/lib/index.js#L94

this on 
`this.emit('close', error)`
