### ISSUE TITLE
net.createConnection is not a function

### ISSUE THREAD

**Issue by sarthakgupta0411** [mkozjak/node-telnet-client#114]
Hello. I've been trying to set up a telnet-client connection within an app I'm developing using ionic. Every time I run the app, I get the following runtime error: net.createConnection is not a function. I'm confused on how to solve this so that I can connect to the server. Thanks

**Comment by mkozjak** [comment]
Hello. By default, you cannot use node's net library in ionic. Tried something like this? https://github.com/theveloped/cordova-chrome-net

**Comment by mkozjak** [comment]
@sarthakgupta0411 please reopen if needed!
