### ISSUE TITLE
First line or character is always missing

### ISSUE THREAD

**Issue by daanoz** [mkozjak/node-telnet-client#115]
Hi,

I've been trying to figure out why the first thing of my response is always missing. Could very well be a configuration issue, but after trying many things, I'm not sure what's left to try.

So, if I use my regular telnet window, I see the following pattern:
```
help
Console commands:
    help|h|?
    ping
    more-stuff

OK
```

When using the node telnet client with this config:
```
{
        shellPrompt: /(OK|KO.*)/,
        timeout: 5000,
        debug: true
}
```
The response contains:
```
    help|h|?
    ping
    more-stuff

OK

```

So I went a bit futher, disabled the line-break check:
```
{
        shellPrompt: /(OK|KO.*)/,
        timeout: 5000,
        debug: true,
        irs: ""
}
```
The concatenated response (`result.replace(/(\n|\r)/g, '')`) response contains:
```
onsole commands:    help|h|?    ping    more-stuff    OK
```

Again the first thing missing; is there a way to get that it as well?

**Comment by mkozjak** [comment]
Hmm, hard to tell, because I'd need to test it myself on the telnet server, but try using `echoLines = 0` first!

**Comment by daanoz** [comment]
That was it! Thanks, tried all numbers from 1 to 5, but not 0...
