### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by rjscruggs** [mkozjak/node-telnet-client#116]
I am unable to get my program to login through your package. I tested logging normally through telnet and works fine and I posted a screenshot below. What am I doing wrong?

```'use strict'

var Telnet = require('telnet-client');
var connection = new Telnet();
var host = "192.168.x.xxx";

var config = {
  host: host,
  port: "23",
  loginPrompt: "Login:",
  passwordPrompt: "Password:",
  username: "user",
  password: "password",
  shellPrompt: 'VMTelnet>',
  negotiationMandatory: false,
  timeout: 15000
}

connection.on('connect', function (err, res) {
    if (err) return err
    console.log("Connected to", host)
})
connection.on('timeout', function (err, res) {
    if (err) return err
    console.log("Socket timeout!")
})
connection.on('close', function (err, res) {
    if (err) return err
    console.log("Connection closed.")
})
connection.on('ready', function (prompt) {
    console.log('Connection is ready!\n' + prompt)
})
connection.on('failedlogin', function (msg) {
    console.log("Login failed!", msg);
})

connection.connect(config)
```

![telnet](https://user-images.githubusercontent.com/34218656/43165848-cab39b8c-8f49-11e8-9c38-ecb5c0afd476.PNG)

And here is the response for trying to connect through node
![connect](https://user-images.githubusercontent.com/34218656/43166063-6a5d7626-8f4a-11e8-9a47-4dfd2e3fee78.PNG)

**Comment by rjscruggs** [comment]
Fixed it myself. For those of you having the same problem, if you're on windows, you need your username and password to be like this

```var config = {
  host: host,
  port: "23",
  loginPrompt: "Login:",
  passwordPrompt: "Password:",
  username: "user\r\n",
  password: "password\r\n",
  shellPrompt: 'VMTelnet>',
  timeout: 15000
}
```

for unix, I would assume '\n'. This is what worked for me

**Comment by mkozjak** [comment]
Interesting. I'll look further into this.
