### ISSUE TITLE
Services with no prompts

### ISSUE THREAD

**Issue by joedeveloper** [mkozjak/node-telnet-client#117]
I am working with a telnet interface that has no discernible prompt string.
What kind of issues would that cause me currently? If any, what workarounds might be suggested?
Thanks All! 

sample ser2net log:
```
2018/08/28 23:11:41 OPEN (192.168.0.109:62004)
?v
V=120:387:4999

```
node output:
```
23:11 $ node ./telnet_poller.js
(node:40873) UnhandledPromiseRejectionWarning: Error: response not received
    at Timeout.setTimeout [as _onTimeout] (/Users/joedev/coder/projects/gogo/code/gogOS/keya_daemon/node_keya_poller/node_modules/telnet-client/lib/index.js:150:47)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:40873) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:40873) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

When killing node script the ser2net log indicates that the tcp connection is closed.

Is it the lack of prompt that is causing failure to read ```res``` or something else?
I am using the await example with node v8.11.4 with only the connection (working) and exec line changed:
```let res = await connection.exec('\r?v\r')```

**Comment by mkozjak** [comment]
@joedeveloper Hi! Try with `negotiationMandatory` option disabled when connecting.

See an example here:
https://github.com/mkozjak/node-telnet-client/blob/master/test/004_negotiation_optional.js

**Comment by mkozjak** [comment]
Reopen if needed.
