### ISSUE TITLE
Bug with responses on one line

### ISSUE THREAD

**Issue by k-yle** [mkozjak/node-telnet-client#120]
Hi, the responses from my telnet server do not have a trailing new line, so they appear on the same line as the next prompt. For instance:
![image](https://user-images.githubusercontent.com/16009897/49324734-db6d2f00-f598-11e8-98b3-24ad0938e910.png)
When I run the equivalent in this library, `await connection.exec('astparam g ch_select')`, I get no response unless I set `stripShellPrompt: false`, in which case the response is, e.g. `0002/ # `. 

I would have expected, since I've set `shellPrompt: '/ # '`, that `connection.exec` would return `0002` in my example.

**Comment by mkozjak** [comment]
Hi, @k-yle, thank you for reporting this bug! This issue is resolved in version 0.16.2.

Btw, is this the Kramer KDS-EN6 video encoder?
