### ISSUE TITLE
How to parse errors from event ?

### ISSUE THREAD

**Issue by noririco** [mkozjak/node-telnet-client#123]
` 
{ Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:111:27) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' }
`

How do I parse this 
Error: read ECONNRESET at TCP.onStreamRead (internal/stream_base_commons.js:111:27)

JSON.stringify will give only errno, code, syscall

**Comment by mkozjak** [comment]
Unfortunately, this is nothing specific to the library itself, so I must close it, but yes, that's standard js object behaviour. What do you want to accomplish?
