### ISSUE TITLE
more than 1 shellPrompt

### ISSUE THREAD

**Issue by noririco** [mkozjak/node-telnet-client#125]
Is it possible to have more than 1 shellPrompt ? 
I have situation like this

for most of the time its 
-->
sometimes its 
-1>
or 
-2>
.....

How can I achieve a this behaviour ?

**Comment by mkozjak** [comment]
You can define regex shellPrompt.
Check here for details: https://github.com/mkozjak/node-telnet-client/blob/master/test/011_dynamic_shellprompt.js#L33
