### ISSUE TITLE
When server is busy, the login process often fails

### ISSUE THREAD

**Issue by MigukNamja** [mkozjak/node-telnet-client#129]
While working with a tool that uses telnet-client, my connections would sometimes (often) return 'failedLogin' whenever the server was busy. I traced it down to this else statement. When I removed this else statement, all of my telnet connections succeeded, no matter how busy my server was.

I believe this else statement is not needed anyways since you protect against infinite loop in the 'if' statement before it.

```
+++ a/lib/index.js
--- b/lib/index.js
@@ -289,7 +289,10 @@ module.exports = class Telnet extends events.EventEmitter {
           this.state = 'login'
           this._login('username')
           this.loginPromptReceived = true
+        } 
-        } else {
-          this.emit('failedlogin', stringData)
-          this.destroy()
-        }
```

Submitted pull-request #128

**Comment by mkozjak** [comment]
Fixed with #128
