### ISSUE TITLE
 My connection always prompts for timeout

### ISSUE THREAD

**Issue by MaxBill** [mkozjak/node-telnet-client#131]
According to the document, I haven't connected successfully. Please help me see the problem.
It is possible to use terminal access services.

My code is as follows：

const Telnet = require('telnet-client');

let telnet = new Telnet();

let params = {
    debug: true,
    port: 6379,
    host: '127.0.0.1',
    timeout: 2000,
    initialLFCR: true,
    shellPrompt: '',
    negotiationMandatory: false
};

telnet.on('data', function (data) {
    console.log(data);
});

telnet.on('connect', function () {
    console.log('connect ok');
});

telnet.on('ready', function () {
    console.log("connect ready");
    connection.exec(cmd, function (err, response) {
        console.log(response);
    });
});

telnet.on('timeout', function () {
    console.log('connect timeout!');
    telnet.end();
});

telnet.on('close', function () {
    console.log('connect closed');
});

telnet.connect(params);

Operation result：
connect ok
connect timeout!
connect closed

![深度截图_选择区域_20190517102353](https://user-images.githubusercontent.com/16558525/57899009-e2a9a000-788d-11e9-8b87-92860cb3522b.png)

**Comment by SvenC56** [comment]
I run into the same problem. I think it has to to with the `shellPrompt`.

**Comment by mkozjak** [comment]
Hi, just to confirm, you're using redis?

**Comment by mkozjak** [comment]
Please reopen if needed!

**Comment by MaxBill** [comment]
Thank you for your help in solving my problem.
