### ISSUE TITLE
Always prompt timeout exceptions using Async and Await

### ISSUE THREAD

**Issue by MaxBill** [mkozjak/node-telnet-client#136]
Always prompt timeout exceptions using Async and Await ,It's OK to use promise. What's the question?

Here is the exception information prompted:
asyncToGenerator.js?0f75:20 Uncaught (in promise) Error: response not received
    at setTimeout (/home/shuai/deve/projbox/PCSPACE/RedisPlus/node_modules/telnet-client/lib/index.js:155)

**Comment by mkozjak** [comment]
There may be many things going wrong here. Add more info or refer an existing issue with sufficient information.

**Comment by MaxBill** [comment]
Running results:
![深度截图_选择区域_20190607174052](https://user-images.githubusercontent.com/16558525/59095558-6a457480-894b-11e9-9b15-276f442576b6.png)


My code is as follows:

const Telnet = require('telnet-client');

let telnet;

export const open = async function (host, port, pass) {
    let params = {
        host: host,
        port: port,
        timeout: 1500,
        negotiationMandatory: false
    };
    telnet = new Telnet();
    console.log("start ...");
    await telnet.connect(params);
    console.log("end ...");
    let execInfo = await telnet.exec('auth ' + pass);
    console.log(execInfo);
};

**Comment by mkozjak** [comment]
Use try/catch blocks and you will catch that error.
It'd also really help if you formatted your code pasted here...

**Comment by MaxBill** [comment]
Sorry, bad code format makes you uncomfortable


I added exception capture. The exception information is as follows:

    excepton:  Error: response not received
       at setTimeout (/home/shuai/deve/projbox/PCSPACE/RedisPlus/node_modules/telnet-client/lib/index.js:155)


The formatted code is as follows:


    const Telnet = require('telnet-client');

    let telnet;

    export const open = async function (host, port, pass) {

        let params = {
           host: host,
           port: port,
           timeout: 1500,
           negotiationMandatory: false
        };
    
        try {
           telnet = new Telnet();
           console.log("start ...");
           await telnet.connect(params);
           console.log("end ...");
           let execInfo = await telnet.exec('auth ' + pass);
           console.log(execInfo);
       }catch (e) {
           console.log("excepton: ",e);
       }

    };

**Comment by mkozjak** [comment]
> Use try/catch blocks and you will catch that error.

Read this one?

**Comment by mkozjak** [comment]
Ok, and what do you expect?

**Comment by MaxBill** [comment]
I'm sorry, but my question wastes your time.

The problem is: the way I use Async/Await is timeout, the way I use Promises is normal, and the state of service is normal. That's why I consult you. Here are two comparisons:

![深度截图_选择区域_20190607194751](https://user-images.githubusercontent.com/16558525/59102391-7e46a180-895e-11e9-8125-30d6554132df.png)
![深度截图_选择区域_20190607195549](https://user-images.githubusercontent.com/16558525/59102398-83a3ec00-895e-11e9-8144-f221a5896e2f.png)

**Comment by mkozjak** [comment]
Wrap `connection.exec` in a try catch and handle it further.
