### ISSUE TITLE
 The loop does not pass the password

### ISSUE THREAD

**Issue by FlowDirosa** [mkozjak/node-telnet-client#138]
Hello, here's my code:

const Telnet = require('telnet-client')
const connection = new Telnet()

let params = {
  host: '10.1.***.***',
  port: 23,
  shellPrompt: 'cannonball',
  loginPrompt: 'Login:',
  passwordPrompt: 'Password:',
  username: 'roomcontrol',
  password: 'Yamaha-CS-700',
  negotiationMandatory: false,
  ors: '\r\n',
  timeout: 1500
}

let cmd = 'get speaker-volume'

connection.on('failedlogin',function(msg) {
    console.log("Login failed !",msg)
})

connection.on('connect', function (err, res) {
    if (err) return err
    console.log("Connected to", params.host)
})

connection.on('ready', function(prompt) {
  connection.send('get speaker-volume', function(err, response) {
    if(response === undefined || err){
      console.log('***** Error *****')
      console.log(err)
    } else {
      console.log('****** Response *******')
      console.log(response)
    }
  })
})

connection.on('close', function() {
console.log('****** connection closed ******')
})

console.log('***** connecting ******')
connection.connect(params)

My shell return this:
![Capture d’écran (22)](https://user-images.githubusercontent.com/29425361/60523816-b508a100-9ceb-11e9-8d1a-f23753f38cb7.png)

Knowing that I checked the password on the shell command directly, it works, where could the problem come from?

**Comment by mkozjak** [comment]
Please reopen if you still have this issue.
