### ISSUE TITLE
Trying to connect to unturned telnet rcon

### ISSUE THREAD

**Issue by KyeNormanGill** [mkozjak/node-telnet-client#141]
Hi!
I'm trying to connect to an unturned servers rcon (that is only telnet).
It works with putty just fine, all I do is put in IP and port, it connects, and I execute `login <password>` then I can run commands. https://i.imgur.com/GAZsCqQ.png

My issue is, I'm not sure how to connect properly with all the connectivity options.

```js
let params = {
	host: '[redacted]',
	port: '27016',
	shellPrompt: '',
	failedLoginMatch: 'Error: You have not logged in yet! Login with syntax: login <password>',
	timeout: 15000,
	execTimeout: 15000,
	debug: true
}
```

I tried setting all the prompts to `login <password>` (but with my actual password) and all I get is
```
Error: response not received
    at Timeout.setTimeout [as _onTimeout] (C:\Unturned\chat_relay\node_modules\telnet-client\lib\index.js:231:26)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
```

Any idea on how I can debug this?

**Comment by mkozjak** [comment]
shellPrompt can’t be ‘’. Define something or use negotiationMandatory false.

**Comment by KyeNormanGill** [comment]
Ahh, thankyou the negotiationMandatory was the fix.
