### ISSUE TITLE
Problem using exec

### ISSUE THREAD

**Issue by guuhx97** [mkozjak/node-telnet-client#144]
Hi
I am having trouble executing a command after the telnet connection is established. Below is the code snippet and the answer.

Code
![image](https://user-images.githubusercontent.com/22873208/65604140-4d29c580-df7d-11e9-893e-1557c20445dc.png)

Answer
![image](https://user-images.githubusercontent.com/22873208/65604229-78141980-df7d-11e9-989b-2162c7c3ba71.png)

Remote device log (Device is Mikrotik)
![image](https://user-images.githubusercontent.com/22873208/65605017-c2e26100-df7e-11e9-9c72-fca68b65ef08.png)

Taking this last image into consideration, I assume the connection was successful and what problem is executing the command.

What would be the problem?

**Comment by wensonH** [comment]
Maybe the reason of your case is:  the command executing time exceed the default value(2000ms)。 if command executing time greater than its default value, you will receive this error. maybe you should try to add the execTimeout option to your connect params. like
`let params = {
...
execTimeout: 10000
...
}
`
