### ISSUE TITLE
Error event is called on successfull connection

### ISSUE THREAD

**Issue by HarryBilney** [mkozjak/node-telnet-client#155]
Hi,

![code](https://user-images.githubusercontent.com/57139561/70999156-c0e8f380-20d0-11ea-8e21-6a14f7a25882.png)

That's my connection code, I still get the error event called which triggers my error message gui straight after my successful message... Any ideas?

**Comment by mkozjak** [comment]
Might be the prompt and/or username/passwords are wrong?

**Comment by mkozjak** [comment]
Closing as it's obsolete.
