### ISSUE TITLE
Typescript definition not correct

### ISSUE THREAD

**Issue by digijap** [mkozjak/node-telnet-client#158]
Using ts-node to run this script
```
import * as Telnet from "telnet-client";


async function run() {
    const connection = new Telnet();

    const params = {
        host: "127.0.0.1",
        port: 5554,
        shellPrompt: "OK\r",
        timeout: 1500
    };

    try {
        await connection.connect(params);
    } catch (error) {
        console.log(error);
    }

    connection.end();
}

run();
```
Gives the following error:
```
src/telnet.ts:9:28 - error TS2351: This expression is not constructable.
  Type 'typeof import("/node_modules/telnet-client/lib/index")' has no construct signatures.

9     const connection = new Telnet();
```

Running with typescript 3.8.2. Any ideas why this is happening?

**Comment by mkozjak** [comment]
@digijap - I guess it's because telnet-client doesn't really have any typescript types defined.
Care to do a PR to be able to use it with typescript?

**Comment by digijap** [comment]
Sure if it's needed but [this PR](https://github.com/mkozjak/node-telnet-client/pull/145) already adds typings right?
I'll look in to fixing them nonetheless

**Comment by mkozjak** [comment]
@digijap - Yup, thank you in advance!

**Comment by digijap** [comment]
After fiddling around a bit with the typescript definition I figured out that I had to add
`"esModuleInterop": true,`
To my tsconfig.json.

Thanks for the quick replies :)
