### ISSUE TITLE
If connect() fails, no exception/error thrown

### ISSUE THREAD

**Issue by loffelmacher** [mkozjak/node-telnet-client#16]
I have code like this: 

		try {
			connection.connect(telnetParams);
		} catch (err) {
			console.error('telnet connection refused');
		}

and whne my server is not running listening on the specified port, the call to `connect()` fails, but I can't trap that exception and continue running my program. I know exception handling in node is a messy thing, Maybe this is standard for node modules, and everyone uses the global error handler. 

Thanks for the module, saved me a lot of trouble brother!

**Comment by mkozjak** [comment]
@loffelmacher, thanks for using the library!

You could work around this using the following approach:
```
    try {
        connection.connect(telnetParams);

        connection.on('error', function(err) {
            throw(err)
        })
    } catch (err) {
        console.error('telnet connection refused:', err);
    }
```

**Comment by loffelmacher** [comment]
thanks for the response. I tried that out and it still blows up, here's the output from my console. doing some bluetooth low-energy stuff and firing off a telnet command in response:

```
bt-central/app.js:38
				throw (err);
				       ^
Error: connect ECONNREFUSED
    at errnoException (net.js:905:11)
    at Object.afterConnect [as oncomplete] (net.js:896:19)
```

**Comment by mkozjak** [comment]
Yeah, true... And using only 'on error' event without try..catch is not an option? You can trigger another function inside the callback function of 'on error' event...

**Comment by loffelmacher** [comment]
what i finally went with was to just have a config option that will prevent it from firing the telnet off if i am only playing around the rest of the code. easy-peasy. thanks for your feedback.
