### ISSUE TITLE
Error: Socket ends

### ISSUE THREAD

**Issue by nigilan** [mkozjak/node-telnet-client#161]
```
 const params = {
    host: '192.168.10.14',
    port: 4001,
    shellPrompt: '/ # ', // or negotiationMandatory: true,
    timeout: 1500,
  };

  connection.on('ready', (prompt) => {
    connection.exec(cmd, (err, response) => {
      console.log(response);
    });
  });

  connection.on('timeout', () => {
    console.log('socket timeout!');
    connection.end();
  });

  connection.on('close', () => {
    console.log('connection closed');
  });

  connection.connect(params);
}
```
I have the above piece of code and when I run the program, it first prints
`connection closed` 
and then it prints (in middleware error handler)
`Error: Socket ends`

I am seeing some issues about `Socket timeout` but not `Socket ends`. And, I am able to connect to telnet server using **Tera Term** and **command prompt**. 

Any leads would be helpful, thanks in advance.

**Comment by mkozjak** [comment]
Is your telnet shell prompt `/ # `?

**Comment by nigilan** [comment]
No, there is no telnet prompt. When I use command prompt, with IP and Port number , it straightaways sends data. I have also tried by disabling `shellPrompt` and used 'negotiationMandatory: false,
' and in all combinations. Output is the same.

**Comment by nigilan** [comment]
@mkozjak Thank you. Now, I tried with `shellPrompt: '' ` and the incoming stream is available in `prompt` variable.
