### ISSUE TITLE
Connecting to RadioRA 2 system

### ISSUE THREAD

**Issue by draperw** [mkozjak/node-telnet-client#162]
I'm using the telnet client (current 1.2.11) via node-red-contrib-lutron to control Lutron lighting systems. Lutron has more than 1 product line, but all use the same Telnet login credentials and commands. The Telnet component works fine for the newer product line Caséta. It does not work for the older (about 2011 design) RadioRA 2 system. The RadioRA 2 hardware is kind of finicky around anything to do with networking. But I've never had a Telnet issue. 

The login sequence for both products from a terminal session:
bl@MBP ~ % telnet 192.168.1.18
Trying 192.168.1.18...
Connected to lutron-ra2-main.lan.
Escape character is '^]'.
login: lutron
password: integration

GNET> 
__________________
The only difference between the 2 products is that RadioRA 2 system has the line feed before the GNET> prompt and Caséta system does not.

Here is the error stream from the node server:

Unhandled rejection Error: Cannot connect                                                                            
    at Socket.socket.setTimeout (/data/node_modules/telnet-client/lib/index.js:85:25)                                
    at Object.onceWrapper (events.js:286:20)                                                                         
    at Socket.emit (events.js:198:13)                                                                                
    at Socket._onTimeout (net.js:443:8)                                                                              
    at ontimeout (timers.js:436:11)                                                                                  
    at tryOnTimeout (timers.js:300:5)                                                                                
    at listOnTimeout (timers.js:263:5)                                                                               
    at Timer.processTimers (timers.js:223:10)

Any ideas? Thanks

**Comment by mkozjak** [comment]
Hi, please provide your connection code so we can debug.

**Comment by draperw** [comment]
Here is the code. Note that in doing more investigation those errors are being generated for both systems. But the connection seems to be working in the Caséta case as there is output shown in debug nodes in node-red. Thanks

```
var Telnet = require('telnet-client');
    var events = require("events");

    module.exports = function (RED) {

    function LutronConfigNode(config) {
        RED.nodes.createNode(this, config);
        this.lutronLoc = config.ipaddress;
        var node = this;
        node.connected = false;
        node.telnet = new Telnet();
        node.port = 23;
        this.deviceMap = config.deviceMap;
        node.devices = {};
        node.lutronEvent = new events.EventEmitter();
        var params = {
            host: this.lutronLoc,
            port: this.port,
            shellPrompt: 'GNET>',
            debug: true,
            username: 'lutron',
            password: 'integration',
            timeout: parseInt(config.timeout) || 45000
        };
        this.sendLutronCommand = function (devId, val) {
            var str = '#OUTPUT,' + devId + ',1,' + val;
            this.telnet.getSocket().write(str + '\n');
        };
        this.sendLutronStatus = function (devId) {
            var str = '?OUTPUT,' + devId + ',1';
            this.telnet.getSocket().write(str + '\n');
        };
        this.telnet.on('data', (function (self, pkt) {
            self.lutronRecv(pkt);
        }).bind(null, node));
        this.telnet.on('connect', function () {
            this.connected = true;
            console.log('telnet connect');
        });
        this.telnet.on('close', function () {
            this.connected = false;
            console.log('telnet close');
        });
        this.telnet.on('error', function () {
            console.log('telent error');
        });
        this.telnet.on('failedlogin', function () {
            console.log('telent failed login');
        });
        this.lutronSend = function (msg, fn) {
            this.telent.getSocket().write(msg + '\n', fn);
        }
        this.lutrongUpdate = function (deviceId, fn) {
            this.lutronSend('?OUTPUT,' + deviceId + ',1', fn);
        }
        this.lutronSend = function (deviceId, val, fn) {
            this.lutronSend('#OUTPUT,' + deviceId + ',1,' + val, fn);
        }
        this.lutronRecv = function (data) {
            var st = data.toString().trim();
            var cmd = st[0]
            var cs = st.substring(1).split(',')
            var type = cs[0]
            if (cs.length > 3) {
                var deviceId = parseInt(cs[1])
                var action = parseInt(cs[2])
                var param = parseFloat(cs[3])
                //              console.log('[',cmd,',', type, ',',deviceId,
                //              ',', action,',', param,']')
                this.lutronEvent.emit('data', {
                    cmd: cmd,
                    type: type,
                    deviceId: deviceId,
                    action: action,
                    param: param
                });
                if (cmd == '~') {
                    // event notification
                    if (type == 'OUTPUT' && action == 1) {
                        this.devices[deviceId] = param
                        //this.scheduleLoxoneUpdate(deviceId, action, param)
                    } else if (type == 'DEVICE') {
                        //this.scheduleLoxoneUpdate(deviceId, action, param)
                    }
                }
            }
        }
        this.telnet.connect(params);
    }
    RED.nodes.registerType('lutron-config', LutronConfigNode);
} 
```

**Comment by mkozjak** [comment]
Please reopen if needed.
