### ISSUE TITLE
Unhandled rejection Error: Cannot connect

### ISSUE THREAD

**Issue by amitshrestha221** [mkozjak/node-telnet-client#172]
I implemented this, https://www.npmjs.com/package/telnet-client
package in my project.

My JS file :

```

var Telnet = require('telnet-client')
var connection = new Telnet()

var params = {
    host: '128.199.19.53',
    port: 23,
    shellPrompt: '/ # ',
    timeout: 1500,
    // removeEcho: 4
}


connection.connect(params)


```

Output :

![image](https://user-images.githubusercontent.com/14818467/81560408-12ac5600-93b1-11ea-97af-a94929b29cd3.png)

I've been struggling with this error. Anyone who have implemented this before? Thanks in advance.

**Comment by mkozjak** [comment]
Why are you using this prompt?

**Comment by amitshrestha221** [comment]
Sir are you referring to the prompt inside the params?

**Comment by mkozjak** [comment]
That’s right!

**Comment by amitshrestha221** [comment]
Sir it was in the documentation, I just followed the example in the doc. I even commented it and put just host and port in the params, still same issue. Can you please enlighten me with a bit more elaboration?

**Comment by mkozjak** [comment]
Connect to your telnet server, copy the shell prompt and set it into the library. It’s all in the documentation. Examples are not there just to copy/paste them around.
