### ISSUE TITLE
"console-output" not emitted

### ISSUE THREAD

**Issue by mikeper030** [mkozjak/node-telnet-client#175]
I came across the following source code in the VPN ht app

    function OpenVPNLog() {
      return new Promise(function (resolve,reject) {
          console.log("starting logging")
          connection.exec('log on all').then((response)=>{

            console.log("log"+ response);
            connection.exec('state on').then((logsResponse)=> {
                console.log("state" + logsResponse);
                connection.exec('hold release').then((logsResponse) => {
                    connection.on('console-output', function (response) {
                        console.log("out" + response);
                        _.each(response.split("\n"), function (res) {
                            console.log("response: " + res)
                            if (res && res.substr(1, 5) == 'STATE') {
                                openvpnEmitter.emit('state-change', res.substr(7).split(","));
                            } else if (res && res.substr(1, 4) == 'HOLD') {
                                openvpnEmitter.emit('hold-waiting');
                            } else if ((res && res.substr(1, 5) == 'FATAL') || (res && res.substr(1, 5) == 'ERROR')) {
                                openvpnEmitter.emit('error', res.substr(7));
                            } else if (res && res.substr(1, 9) == 'BYTECOUNT') {
                                openvpnEmitter.emit('bytecount', res.substr(11).split(","));
                            } else if (res && res.substr(0, 7) == 'SUCCESS') {
                                if (res.substr(9, 3) == 'pid') {
                                    openvpnEmitter.emit('pid', res.substr(13));
                                }
                            } else {
                                if (res.length > 0) {
                                    console.log("response: " + res)
                                    openvpnEmitter.emit('console-output', res);
                                }
                            }
                        });

                    });
                    console.log("ok")
                    resolve("ok");
                });
            });
        });
    })

}

i do succeed to establish connection and run the commands there. however the event 'console-output' is never triggered. by looking through your source code i see that it is not even implemented. can someone help me figure it out?
Thank in advance!

**Comment by mkozjak** [comment]
Why would `console-output` event be emitted from my lib?

**Comment by mikeper030** [comment]
I guess they modified your code. Can you think of a way to implement continuesly logging event like this? Thanks.

**Comment by mkozjak** [comment]
No. If you have a solution to your issue or you want to propose a new feature, feel free to provide a PR and I'll gladly review it. You can also hire me if you want to get a certain feature developed into this project!

https://github.com/mkozjak/node-telnet-client#professional-support
