### ISSUE TITLE
default install not installing stream or net dependencies

### ISSUE THREAD

**Issue by jmurdick** [mkozjak/node-telnet-client#176]
Ran "npm install telnet-client" and when doing "ng build" for Angular got the following errors:

![image](https://user-images.githubusercontent.com/11596694/86003260-28182680-b9d7-11ea-881d-ddf50afe8f72.png)

Install "net" and "stream" manuall results in other errors that require changes to the polyfills.ts file.  Aside from the initial dependencies that aren't installing, these other issues appear to result from the extreme age and lack of updates to the node-telnet library itself.

**Comment by mkozjak** [comment]
@jmurdick any possible improvements you could make via PR?

**Comment by mkozjak** [comment]
Since this case isn’t the core issue for this lib, please submit a PR stating the needed procedure to install those libs in the readme.
