### ISSUE TITLE
change timeout on .send after connect

### ISSUE THREAD

**Issue by noririco** [mkozjak/node-telnet-client#177]
Hi, is it possible to change timeout after connection was made?

My situation is like this:
Connection timeout should be 4 sec when I try to connect,
otherwise I want it to be like 60 min

Thanks!

**Comment by mkozjak** [comment]
Hi, you could use connection.exec timeout argument with all your requests.

**Comment by noririco** [comment]
can you explain please more what is connection.exec timeout argument ?
I use as options

```
let telnetConnectionOptionParams = {
  host: "",
  port: 4000,
  shellPrompt: promptRegex,
  timeout: 4000,
  negotiationMandatory: false,
  debug: console.log
};

```
host is set just before connection is made

  ```
return telnetConnection
    .connect( telnetConnectionOptionParams )
    .then( prompt => {
```

I send  _command.timeout === 6000000
```
return telnetConnection
    .send(
      _command.msg,
      {
        timeout: _command.timeout ? _command.timeout : 10,

```

but this is timeouts after 4000 ms

**Comment by mkozjak** [comment]
Maybe there's a bug in the library. Care to debug and provide a fix if needed, please?

**Comment by noririco** [comment]
Is it just possible to change  the socket timeout after connection is made ?

**Comment by mkozjak** [comment]
@noririco actually, see sendTimeout parameter here: https://github.com/mkozjak/node-telnet-client/blob/master/README.md#connectionconnectoptions---promise

Should work.
