### ISSUE TITLE
prompt searching doesn't account for regular expressions

### ISSUE THREAD

**Issue by srgraham** [mkozjak/node-telnet-client#18]
```
/node_modules/telnet-client/lib/telnet-client.js:155
    promptIndex = stringData.search(telnetObj.shellPrompt);
                             ^
SyntaxError: Invalid regular expression: /*/: Nothing to repeat
```

The problem is that the telnetObj.shellPrompt tries to convert to a regular expression, as documented here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/search#Parameters

The regular expression may not be valid, for instance with the string "*", it crashes.

To fix this, there needs to be some regular expression escaping going on here. Here's an example function that handles that: http://stackoverflow.com/questions/3446170/escape-string-for-use-in-javascript-regex#answer-6969486

**Comment by mkozjak** [comment]
Thanks for the report!

All credit goes to bobince:
http://stackoverflow.com/questions/3561493/is-there-a-regexp-escape-function-in-javascript/3561711#3561711

**Comment by srgraham** [comment]
Thanks! Noticed an issue with it though. Strings for shellPrompt, loginPrompt, and passwordPrompt work fine, but supplying regexes to them do not.

For instance, setting shellPrompt to /#/ will instead create the regex /\/#\//

What I'd suggest is having the regexEscape() check whether the input is an instance of RegExp and return it exactly as is if so. Otherwise, it'll go through with the escaping.

**Comment by mkozjak** [comment]
Will check on that one. Thanks!

**Comment by srgraham** [comment]
I did a bit of coding on this, but haven't fully tested it. It's probably very incomplete. Here it is if you want to continue where I left off: https://github.com/mkozjak/node-telnet-client/compare/master...srgraham:master

**Comment by mkozjak** [comment]
@srgraham: Will definitely look into it. Thanks!
