### ISSUE TITLE
Can't log in : password never accepted

### ISSUE THREAD

**Issue by fortinmike** [mkozjak/node-telnet-client#180]
I've been trying to figure out why `telnet-client` fails to connect to my telnet server. I've read most of the issues related to login but didn't find anything that helps. I've tried stepping through the`telnet-client ` code to see what is going on and I can confirm that the library does connect and write the username and then proceeds to the password prompt. It then writes the password to the socket.

However, the password is never accepted (my `failedLoginMatch` triggers). I've tried the defaults, as well as tweaking `ors`, etc., but nothing worked thus far and nothing is wrong in the library's logic as far as I could see.

So I'm out of ideas at the moment.

## My prompt looks like this (manually, using Windows telnet)

**Successful login:**

```
Numato Lab Wifi GPIO32 Module
Enter your user name and password to login
User Name: admin
Password:
Logged in successfully

>
```

**Bad username:**

```
Numato Lab Wifi GPIO32 Module
Enter your user name and password to login
User Name: asefasefasef
Password: # <=== I never get a chance to type a password here, the next line ("Bad user") is instantly displayed
Bad user: access denied
```

**Wrong password:**

```
Numato Lab Wifi GPIO32 Module
Enter your user name and password to login
User Name: admin
Password:
Access denied # <=== This is the response I'm getting!
```

## My connection settings

```
connection.connect({
      host,
      port,
      loginPrompt: /User Name: /i,
      passwordPrompt: /Password: /i,
      failedLoginMatch: /Access Denied/i,
      shellPrompt: />/,
      username: "admin",
      password: "mypassword",
      timeout: 10000,
      debug: true,
    });
```

Any idea what might be causing the password to be rejected? Are there some more things I should try to make my server accept the password?

(I've triple-checked the password itself and everything works alright when connecting on the command-line, but login fails in `telnet-client`)

**Comment by fortinmike** [comment]
Thanks for the tip @mkozjak, I'll try this as soon as I can and will report back.

**Comment by mkozjak** [comment]
Reopen if needed. Thanks!
