### ISSUE TITLE
[Question] How to active debugging

### ISSUE THREAD

**Issue by abdrozak20** [mkozjak/node-telnet-client#186]
I want to debug my code, because cannot connect to router when i telnet use this package, and i already activate debug = true. but still nothing happen.
const extra_options = {
            timeout : 60000,
            execTimeout : 20000,
            sendTimeout : 990000,
            maxBufferLength : 9000000,
            failedLoginMatch : new RegExp(/.*User login failure.*/i),
            loginPrompt : "Username:",
            passwordPrompt : "Password:",
            shellPrompt : new RegExp(/[A-Za-z0-9\-_@]*[>]+$/i),
            debug : true
        };
        
var x = new TelnetOLT(host, telnet_port, telnet_username, telnet_password, extra_options);
return x.connect()

please help. i really need help.
thanks in advice

**Comment by mkozjak** [comment]
Hello! Unfortunately, #41 still hasn’t been resolved. You can only go into the code and debug it manually for now.
