### ISSUE TITLE
loginfailed event never emitted

### ISSUE THREAD

**Issue by brozeph** [mkozjak/node-telnet-client#19]
Even when `loginFailedPrompt` is supplied as documented, the `loginfailed` event is never fired.

**Comment by mkozjak** [comment]
@EyePulp : Is the merged fix working for you? What is your exact use case?

**Comment by EyePulp** [comment]
Sorry for the delayed response.  The merged fix has been working for me.  @brozeph could you post or make a gist of the relevant code?  And just verifying, have you looked in your npm_modules to verify that you're running the new code?

**Comment by ptdongguan** [comment]
this.telnetSocket.on('error', function(error) {
console.log(error);
    // self.emit('error', error);
  });
here problem emit error, i guess it is because of connection still not ready to handle error (cannot connect for wrong ip etc).
after fix like this. the connection will emit close after a while.

**Comment by brozeph** [comment]
@EyePulp @mkozjak - here's what I've noticed...

The [documentation](https://github.com/mkozjak/node-telnet-client/blob/master/README.md#event-loginfailed) indicates to use `loginfailed`

However, in the [code](https://github.com/mkozjak/node-telnet-client/blob/master/lib/telnet-client.js#L154), the event that is fired is actually named `failedlogin`.

**Comment by brozeph** [comment]
@EyePulp a gist for how I use it here: <https://gist.github.com/brozeph/9f634807513bfe25992f>

In the first comment, I provide an example. Please note that I sanitized this code from a working project and made some changes - it might require some tweaking.

**Comment by mkozjak** [comment]
@brozeph: Thanks for reporting. I believe the wrong event name was your issue, then? I've fixed the documentation appropriately.
