### ISSUE TITLE
loginPromt has no method 'replace'

### ISSUE THREAD

**Issue by onion-soup** [mkozjak/node-telnet-client#20]
When trying to open the connection, [loginPromt](https://github.com/mkozjak/node-telnet-client/blob/master/lib/telnet-client.js#L144) is not recognized as a string thus `regexEscape` method fails by saying `replace is undefined`

**Comment by mkozjak** [comment]
@onion-soup, thanks for the ticket! Can you try updating the library and testing again?

Btw, what was your use case? loginPrompt with a non-string value?

**Comment by onion-soup** [comment]
@mkozjak,  yes it works now. The use case was simply trying the [example from readme](https://github.com/mkozjak/node-telnet-client#example-usage). And the problem was that the default value of `loginPrompt` `'/login[: ]*$/i'` was causing the crash.

thanks for the fix!

**Comment by mkozjak** [comment]
@onion-soup, Thanks for helping out!
