### ISSUE TITLE
Synchronous exec

### ISSUE THREAD

**Issue by jgroom33** [mkozjak/node-telnet-client#22]
I'd like the exec function to accept multiple commands with an option to end the session if an error response variable is recognized.
Is there a way to utilize the exec function without invoking the callback?

In the below code, the console prints:
3
3
3

```javascript
    var myStringArray = ["command 1","command 2","command 3"];
    var arrayLength = myStringArray.length;

    connection.on('ready', function (prompt) {
        for (var i = 0; i < arrayLength; i++) {
            connection.exec(myStringArray[i], function (response) {
                console.log(i);
            });
        }
    });
```

**Comment by mkozjak** [comment]
Hi, @jgroom33. I believe there's no way to use another exec without using the previous one's callback with the current implementation, if I understand you correctly.

One way is to use async.each and call its callback with an error if one occurs.
https://github.com/caolan/async#each

Cheers.
