### ISSUE TITLE
Error: connect ECONNREFUSED 192.168.6.25:8100 at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)

### ISSUE THREAD

**Issue by Mattperkinsee** [mkozjak/node-telnet-client#220]
I seem to get a lot these errors only on Linux machines. I can't seem to get this error while running my code on in a Windows environment. Any ideas what might be causing this?

I believe I am creating a bunch of Telnet connections and might be hitting some sort of limit on the Linux machines, but I'm unsure what that might be.

Thanks!

**Comment by mkozjak** [comment]
Is port 8100 opened at all?

**Comment by Mattperkinsee** [comment]
Yes, I would think so. CentOS might be blocking something. I can get it work, but it seems to throw more errors and happen more frequently the more connections that I open. I haven't narrowed it down quite, yet. Like I said though, I can not get any errors to happen on my Windows machine so it's a bit puzzling.

**Comment by Mattperkinsee** [comment]
The issue is very intermittent. I can run it back to back on the Linux machines and sometimes no error and other times there are errors. I am doing a connection.end, should I try connection.destroy instead?

**Comment by Mattperkinsee** [comment]
I think the issue might be that I'm sending too many requests at one time for the server to handle. My Windows machine is slower so this might make sense.

**Comment by Mattperkinsee** [comment]
This was the issue. Sorry about this. Apparently, I was throwing too many requests at once. I added a delay and this alleviated the issue completely every time. Thanks!
