### ISSUE TITLE
Error: Cannot connect

### ISSUE THREAD

**Issue by xinthose** [mkozjak/node-telnet-client#228]
I am trying to connect to the telnet management port on my OpenVPN server from a Windows 10 PC.  I can login manually on Windows with telnet on the command prompt:

```cmd
telnet
open 10.1.1.196 7505
ENTER PASSWORD:
I copy and paste my password here, then the connection succeeds and I can run OpenVPN commands
```

My `telnet-client` config for `connect`:

```json
{
    "host": "10.1.1.196",
    "port": 7505,
    "passwordPrompt": "ENTER PASSWORD:",
    "password": "ABC123",
    "timeout": 5000,
    "debug": true,
    "ors": "\r\n"
}
```

```typescript
await this.telnet.connect(config);    // throws "Error: Cannot connect"
```

There is no `username` for login, so do I need to tell the library to skip that or something?

**Comment by mkozjak** [comment]
Try using negotiationMandatory: false.

**Comment by xinthose** [comment]
> 

I tried that and now get this error: `Error: response not received`.  In my OpenVPN server logs it shows this:

```log
2023-01-02 16:34:06 MANAGEMENT: Client connected from [AF_INET][undef]:7505
2023-01-02 16:34:25 MANAGEMENT: TCP recv error: Connection reset by peer
2023-01-02 16:34:25 MANAGEMENT: Client disconnected
```

**Comment by xinthose** [comment]
I have decided not to use this library.  I got things working correctly by using the Node.js [`net`](https://nodejs.org/api/net.html#class-netsocket) library like in this [project](https://github.com/AuspeXeu/openvpn-status/blob/master/openvpn.js).
