### ISSUE TITLE
Warning: Did not expect server HTML to contain a <div> in <div>.

### ISSUE THREAD

**Issue by backygrumsendev** [mkozjak/node-telnet-client#231]
Uncaught TypeError: Cannot read properties of undefined (reading 'prototype')

![Screenshot 2023-03-14 at 17 25 43](https://user-images.githubusercontent.com/84767372/225072017-80c758de-fdff-4177-8888-42bbbe0bf1bb.png)

**Comment by mkozjak** [comment]
I'm sorry, I don't understand what this is.

**Comment by backygrumsendev** [comment]
It is already resolved. Update of axios was needed.
