### ISSUE TITLE
global install ?

### ISSUE THREAD

**Issue by maboiteaspam** [mkozjak/node-telnet-client#29]
Hi,

Have you checked about it ?

I m afraid it does not work, unless i m wrong.

The package.json is missing the bin field. and if the bin file should be, https://github.com/mkozjak/node-telnet-client/blob/master/lib/telnet-client.js, then i m afraid it s missing the shebang.

```
#!/usr/bin/env node
```

I personally do like this, i work both on windows and linux systems.
https://github.com/maboiteaspam/screenshot-stream-selected/blob/master/bin.js

hth.

**Comment by mkozjak** [comment]
@maboiteaspam: No, 'global install' (npm install -g telnet-client) means just like in every other nodejs library. Simply the library is copied to a global location (perhaps in /usr/local/lib/node_modules on *nix systems, depending on the NODE_PATH variable optionally) and not in your project's directory. There shouldn't be any binaries in this package, hence why there's no 'bin' field in package.json.

Thanks for the feedback!

**Comment by maboiteaspam** [comment]
o i see now. thanks for your answer. Just in case, and because you gave some me doubts ! 
https://nodejs.org/api/modules.html#modules_loading_from_the_global_folders
