### ISSUE TITLE
Can't figure it out how to use it ('ready' state never reached)

### ISSUE THREAD

**Issue by brunokrebs** [mkozjak/node-telnet-client#30]
Hello there, I'm trying to use this module but I can never reach 'ready' state. That is, my timeout callback function is always called.

Check out my gist: https://gist.github.com/brunokrebs/7abd6e9811fd1f50be22

By the way, issuing cli commands, I'm able to reach that same ip + port...

What am I doing wrong?

Thanks in advance.

**Comment by mkozjak** [comment]
Hello!

Most probably your ahell prompt is not '/ # '. 
Can you see what the prompt looks like via cli tools and copy it to your code?

**Comment by dmichel76** [comment]
Sorry to jump on this thread, but I have a very similar issue trying to connect to a telnet server written in Python: https://gist.github.com/dmichel76/d530da8b2da6e51b5cd4

It never gets to the 'ready' state and and a 'timeout' event. That said, if I issue a command (i.e. connection.exec in the callback of the 'connect' event, the server received it properly, but I don't get any response.

connection.on('connect', function(prompt) {
  connection.exec(cmd, function(err, response) {
    console.log(response);
  });
});

Any idea what is going wrong here?

**Comment by mkozjak** [comment]
@dmichel76: This is expected behaviour, as you never send a prompt from your server.

I only got this when using 'telnet' command to telnet to your telnet server:
```
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
```

**Comment by dmichel76** [comment]
OK, but I'm not sure why this would be the desired behaviour. A command line telnet client can send and receive messages without the server sending a prompt, so why would this library expect one?

**Comment by dmichel76** [comment]
Also, from a naive user point of view, I would expect setting shellPrompt: '' to solve the problem ?

**Comment by mkozjak** [comment]
That would match strange stuff. :)

The only way to work this out is to set a new method which just sends a command, ignoring the shell prompt. We would then return a streams interface from it, meaning you'd probably end up parsing all the data there is.

Thinking again, if you don't use any prompts (login, user, password) and no telnet negotiation stuff, what is the point in using this library? I see you just receive data and parse it roughly (self.socket.recv(1024)).
You can just use net.createClient (or net.connect and write to the socket) and parse your stuff.

Either way, this is an interesting feature and I will try to implement it!

**Comment by dmichel76** [comment]
>if you don't use any prompts (login, user, password) and no telnet negotiation stuff, what is the point in using this library?

Yes, I agree that most telnet client/servers will be using the typical prompt, login, user, etc. 

However, I've also seen lots of code (like the python code in the gist I pointed to) that uses the telnet wrapper around the low-level TCP communication stuff to be able to send ASCII messages easily between devices. It's especially true with hardware devices/instruments that often implement a telnet-like server to communicate with it without the whole protocol of using a prompt, a user login, etc.

> You can just use net.createClient (or net.connect and write to the socket) and parse your stuff.
Yes, that's what I'm trying to do now actually :-)

>Either way, this is an interesting feature and I will try to implement it!
That'd be great. As I said earlier, if the CLI telnet client can do, and I tihnk your library ought to be able to cope with that situation too, making it even more complete :-)

**Comment by mkozjak** [comment]
Thanks for the input! :)

**Comment by mkozjak** [comment]
@dmichel76: This is now implemented, so you can switch back. ;)

**Comment by dmichel76** [comment]
Great, thanks for implementing this! I'll be trying it out very shortly :-)

**Comment by mkozjak** [comment]
@dmichel76: Will be available in 0.9.0 on npm shortly.

**Comment by dmichel76** [comment]
@mkozjak Just tried it - great stuff, thanks!

Quick question: what's _ors _and _waitfor _in the _send _command?

**Comment by mkozjak** [comment]
@dmichel76: Thanks for testing out!

```ors``` is an 'output record separator', meaning that string will be appended to your command. It's mainly used for line termination and feeds.
```waitfor``` is a string the library needs to wait for to return the results from ```send``` (up to that very string). If it's not defined, the defined/default timeout will be used.

**Comment by dmichel76** [comment]
Cheers. 

I realised this was explained in your README file right after asking the question (doh!) :-)

**Comment by dmichel76** [comment]
One problem that I encounter is that, when connecting, a server can spit out a lot of text (e.g. a long welcome message) that ends up with '\n'. In this case, the actual response from the send command can be missed.

Would there be a way to ignore the welcome message that is sent when connecting although no command has been sent yet ?

**Comment by mkozjak** [comment]
Let's continue on #45 :)
