### ISSUE TITLE
Problems finding end of response

### ISSUE THREAD

**Issue by papaburgs** [mkozjak/node-telnet-client#31]
Was not able to find a command prompt (supplied as regex or string).

was able to resolve locally by changing code near line 118 to not use indexOf and instead use this for the if statement: `if (!telnetObj.shellPrompt.test(stringData) && stringData.length !== 0) {`

If the prompts are regex, shouldn't `indexOf` be the `search` function or a method like above

**Comment by mkozjak** [comment]
That's correct. Pull request, maybe?
