### ISSUE TITLE
Sequential commands: repeat executions/input buffer messy

### ISSUE THREAD

**Issue by ethanyu94** [mkozjak/node-telnet-client#36]
I'm having trouble sending multiple commands sequentially. Commands are being executed repeatedly, and sometimes the previous entered text is still in the input (e.g. login username appears as a command). I have tried putting the second exec immediately after first exec, in the callback of the first exec, and also maintaining a queue of commands and sending the next exec on 'writedone'. The results are also indeterministic, sometimes it sort of works and sometimes it's very wrong. Here are some sample outputs. Any advice, or is this use case not supported? Thanks!

Exec immediately after: https://gist.github.com/ethanyu94/e99daec29229170fbc82
Result: 
```
$node telnet.js
connection ready
response: -bash: ethanyu: command not found
$echo hello
hello
$echo goodbye
goodbye
response: -bash: ethanyu: command not found
$echo hello
hello
$echo goodbye
goodbye
socket timeout!
connection closed
$
```

Exec on callback: https://gist.github.com/ethanyu94/a2aa08817be4df97c45e
Result:
```
$node telnet.js
connection ready
response: -bash: ethanyu: command not found
$echo hello
hello
response: goodbye
socket timeout!
connection closed
$
```

Exec on writedone: https://gist.github.com/ethanyu94/1bd3f04119bc0ad85582
Result:
```
$node telnet.js
connection ready
writedone
writedone
writedone
response: -bash: ethanyu: command not found
$echo started
started
$echo hello
hello
$echo goodbye
response: -bash: ethanyu: command not found
$echo started
started
$echo hello
hello
$echo goodbye
response: -bash: ethanyu: command not found
$echo started
started
$echo hello
hello
$echo goodbye
socket timeout!
connection closed
$
```

**Comment by mkozjak** [comment]
The second one is correct.

I have a bug in exec when options are defined. I see you use the same parameters in connect and exec. Remove them from exec until I fix this! Thanks for reporting!

**Comment by ethanyu94** [comment]
Maybe telnet on OS X is just weird. The second one works perfectly on busybox for me as well, which is all I needed. Thank you.

**Comment by mkozjak** [comment]
@ethanyu94: Bear in mind that you can now use promises api so you can yield those methods in a combination with bluebird or co libraries.
