### ISSUE TITLE
Timeout on all remote sites

### ISSUE THREAD

**Issue by dcrockwell** [mkozjak/node-telnet-client#40]
```
var telnet = require('telnet-client');
var connection = new telnet();

var params = {
  host: '66.228.127.34',
  port: 4000,
  shellPrompt: '/ # ',
  timeout: 1500,
  // removeEcho: 4
};

connection.on('ready', function(prompt) {
  connection.exec("login", function(err, response) {
    console.log(response);
  });
});

connection.on('timeout', function() {
  console.log('socket timeout!')
  connection.end();
});

connection.on('close', function() {
  console.log('connection closed');
});

connection.connect(params);
```

This results in socket timeout! every time, even if I change the address to a hostname, or another server, or different port, etc.

**Comment by dcrockwell** [comment]
I have not found a single node.js telnet library that works as advertised. Am I fundamentally doing something wrong?

**Comment by mkozjak** [comment]
@dcrockwell: Does your prompt on server '66.228.127.34' and port 4000 look exactly like '/ # '?
If it's not, you are definitely fundamentally doing something wrong. :)

By simply telneting to that server, you could see that the prompt is 'What be thy name, adventurer? '.

Cheers!

**Comment by dcrockwell** [comment]
Thank you very much for getting back to me so quickly, @mkozjak. I'm a step closer, but still need a bit more assistance:

```
import telnet from "telnet-client";

var connection = new telnet(params);

var params = {
	host: "www.ateraan.com",
	port: 4002,
	shellPrompt: "Enter your character name",
	loginPrompt: "Enter your character name",
	passwordPrompt: "Enter your password",
	username: "myuser",
	password: "1234",
	timeout: 10000,
	debug: true
	// removeEcho: 4
};

connection.on("ready", function(prompt) {
	console.log("TELNET READY");
	connection.exec("look", function(err, response) {
		console.log(response);
	});
});

connection.on("timeout", function() {
	console.log("socket timeout!")
	connection.end();
});

connection.on("close", function() {
	console.log("connection closed");
});

connection.connect(params);
```

This does connect, however the output is:

```
TELNET READY
socket timeout!
connection closed
```

Any ideas to point me in the right direction? I apologize in advance for my ignorance on the subject.

**Comment by mkozjak** [comment]
You're supposed to set 'What be thy name, adventurer? ' for 'loginPrompt', I believe. I cannot tell for sure. First connect manually with the 'telnet' command from your shell and inspect what sentence is supposed to be for what. I doubt the login prompt is 'Enter your character name'.

**Comment by dcrockwell** [comment]
I had changed the server to a different one, I apologize if that complicated things. The "prompt", I presume, is the text that preceeds the first prompt? In that case, would this be the correct string for the new server, given this output from a normal telnet session:

![screen shot 2016-02-14 at 3 15 26 am](https://cloud.githubusercontent.com/assets/53482/13033150/53aa5858-d2c9-11e5-8f29-391e9fbe396c.png)

**Comment by dcrockwell** [comment]
I think this still is within the scope of library issues, except now it's mainly a documentation issue.

Currently the library fails silently if prompts are not set in a specific manner. The documentation I found in the README does not seem to encapsulate the full scope of all requirements for this setting, or its related settings: `loginPrompt`, `passwordPrompt`, etc.

I could solve my own issue with access to documentation that made this issue clear. Perhaps that documentation already exists and I missed it?

**Comment by dcrockwell** [comment]
To be clear, I did change the server to a different one on the second example. This may have complicated things becuase "What be they name, adventurer?" was for the previous example.

In the image below, you can see the exact output from a normal telnet session.

With this output and the code I previously pasted, I'm still getting the socket timout.

![screen shot 2016-02-14 at 3 15 26 am](https://cloud.githubusercontent.com/assets/53482/13033150/53aa5858-d2c9-11e5-8f29-391e9fbe396c.png)

Again, i think this may be a documentation issue, as I can find no way to solve my own issue with the information I can find via the README.md.

**Comment by mkozjak** [comment]
Hi!

You are partially right about the documentation. Although there is a
property called 'loginFailedPrompt' and there is an explanation for that,
the name wasn't that obvious. I have now renamed that to
'failedLoginMatch'. If you set that property to 'Only the Administration
can load this NPC.' (if you provide test/test as credentials) and listen on
an event 'failedlogin', you will get that one right out.

Bear in mind that you need a carriage return for both loginPrompt and
passwordPrompt.

This is a working example (update telnet-client to 0.7.0 first!):


var t = require('telnet-client')
var c = new t()

var params = {
  host: 'ateraan.com',
  port: 4002,
  loginPrompt: "Enter your character name:\r",
  failedLoginMatch: "Only the Administration can load this NPC.",
  passwordPrompt: "Enter your password:\r",
  username: 'test',
  password: 'test',
  timeout: 2000,
  debug: true
}

c.on('failedlogin', function() {
  console.log('login failed')
})
c.on("ready", function(prompt) {
  console.log('ready')
})

c.on('timeout', function() {
  console.log('timeout')
  c.end()
})

c.connect(params)

On Sun, Feb 14, 2016 at 11:29 AM, D. C. Rockwell <notifications@github.com>
wrote:

> To be clear, I did change the server to a different one on the second
> example. This may have complicated things becuase "What be they name,
> adventurer?" was for the previous example.
>
> In the image below, you can see the exact output from a normal telnet
> session.
>
> With this output and the code I previously pasted, I'm still getting the
> socket timout.
>
> [image: screen shot 2016-02-14 at 3 15 26 am]
> <https://cloud.githubusercontent.com/assets/53482/13033150/53aa5858-d2c9-11e5-8f29-391e9fbe396c.png>
>
> Again, i think this may be a documentation issue, as I can find no way to
> solve my own issue with the information I can find via the README.md.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mkozjak/node-telnet-client/issues/40#issuecomment-183868700>
> .
>



-- 
Mario Kozjak

**Comment by dcrockwell** [comment]
Thanks for the update, but it seems there's still some issue:

I just tried that example with 0.7.0 and it's failing with just: "timeout"

I tried with verified good credentials, and with debug set to true.

1. `debug: true` doesn't seem to do anything
2. the failure is silent other than the console.log('timeout');

What do you advise?

**Comment by mkozjak** [comment]
I truly have no ideas, because this code:

```
var t = require('telnet-client')
var c = new t()

var params = {
  host: 'ateraan.com',
  port: 4002,
  loginPrompt: "Enter your character name:\r",
  failedLoginMatch: "Only the Administration can load this NPC.",
  passwordPrompt: "Enter your password:\r",
  username: 'test',
  password: 'test',
  timeout: 2000,
  debug: true
}

c.on('failedlogin', function() {
  console.log('login failed')
})
c.on("ready", function(prompt) {
  console.log('ready')
})

c.on('timeout', function() {
  console.log('timeout')
  c.end()
})

c.connect(params)
```

produces this here:
```
login failed
```

**Comment by dcrockwell** [comment]
It seems that I was banned from ateraan.com because "anything that looks like a bot will be banned".

An unfortunate turn of events considering this was meant to just facilitate a different kind of human input into the telnet game, but it's their game and if they don't want this kind of thing then it's their prerogative.

I'll let you know if I need any more assistance, but I think we've reached the end of this thread. Thank you for all your help.

**Comment by mkozjak** [comment]
No problem, thanks for using the library.

Cheers!

On Mon, Feb 15, 2016 at 6:15 PM, D. C. Rockwell <notifications@github.com>
wrote:

> It seems that I was banned from ateraan.com because "anything that looks
> like a bot will be banned".
>
> An unfortunate turn of events considering this was meant to just
> facilitate a different kind of human input into the telnet game, but it's
> their game and if they don't want this kind of thing then it's their
> prerogative.
>
> I'll let you know if I need any more assistance, but I think we've reached
> the end of this thread. Thank you for all your help.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mkozjak/node-telnet-client/issues/40#issuecomment-184308978>
> .
>



-- 
Mario Kozjak
