### ISSUE TITLE
does not connect

### ISSUE THREAD

**Issue by astutesoftware** [mkozjak/node-telnet-client#42]
Hi i am connecting to a simple telnet server that has no authentication and i keep getting 'socket timeout!'

var telnet = require('telnet-client');
var connection = new telnet();

var params = {
  host: 'rainmaker.wunderground.com',
  port: 23,
  shellPrompt: '/ # ',
  timeout: 1500,
 debug: true
};

connection.on('ready', function(prompt) {
  connection.exec('help', function(err, response) {
    console.log(response);
  });
});

connection.on('timeout', function() {
  console.log('socket timeout!')
  connection.end();
});

connection.on('close', function() {
  console.log('connection closed');
});

**Comment by mkozjak** [comment]
Your shell prompt is wrong.

When I tried telnetting to your server, I got 'Press Return to continue:' as a first prompt. Try with that one.

**Comment by astutesoftware** [comment]
aha.. thanks it worked.
Another question. how do i send a ENTER key to the telnet session
connection.exec('\\r\\n', function(err, response) ?

**Comment by mkozjak** [comment]
Yeah. Depends if it's unix or windows. Should be okay.
