### ISSUE TITLE
async data event

### ISSUE THREAD

**Issue by brunogoossens** [mkozjak/node-telnet-client#43]
Is it possible to create an event when data is received from the telnet server? I have a telnet server that sends status changes of my garage port on my arduino. This data is received without first sending a command. Is this possible? I can't find this event in the documentation.

**Comment by mkozjak** [comment]
Hello!

We should generally be able to do such thing. I believe that would mean that we could forward the 'data' event from 'net' library, but would need to keep track for the possible active telnet session, meaning all the 'data' events. I will look into it. Thanks for the request!

**Comment by mkozjak** [comment]
@brunogoossens: This is now available in a master branch. Can you pull it from git and report the results back? I've tested it on my server and it worked as expected.

Usage example:
```js
var connection = new telnet()

connection.on('data', function(data) {
    console.log(data.toString())
})
```

**Comment by brunogoossens** [comment]
Thx. Looks good!
