### ISSUE TITLE
return only appropriate data on 'send'

### ISSUE THREAD

**Issue by mkozjak** [mkozjak/node-telnet-client#45]
There's a problem where all the data before the first ```send``` is received (ie. with a welcome message).
References #30

**Comment by mkozjak** [comment]
@dmichel76 - As it seems there's no way for me to check up on that. This behaviour is similar to the one if you were able to send data so fast after connecting with the ```telnet``` command and sending out data so that all the communication is under the same tcp session. I only get what the server sends to me, so I cannot catch on my own sent data so I can move around the returned data. I cannot determine clearly where the actual data is. This is why we use the telnet specification. To see where we are and what belongs to what.

Even if I hacked around it and places a flag that the message is sent and what particular message it is, I would need to place that string back in the received stream, but then again, I would need to know where to place it. That's too hacky and could yield unexpected behaviour.

You will need to handle this stuff on your own.

**Comment by dmichel76** [comment]
Yes, I understand. Thanks for looking into it anyway!
