### ISSUE TITLE
Exec not exec'ing

### ISSUE THREAD

**Issue by ericuldall** [mkozjak/node-telnet-client#46]
I'm trying to test some commands on a remote mx server and after I successfully connect, the exec command i'm running is not completing.

```
    var telnet = require('telnet-client');
    var connection = new telnet();
    var params = {
        host: _this.mx_records[0].exchange,
        port: 25,
        shellPrompt: '',
        timeout: 1500,
        debug: true //doesn't seem to do anything
    };
    var exec_params = {
        shellPrompt: '',
        timeout: 1500,
        debug: true //doesn't seem to do anything
    };

    connection.on('ready', function(prompt){
        console.log(prompt); //this works!
        connection.exec('HELO hi', exec_params).then(function(res){
            console.log(res); //nothing here!
        }, function(err){
            console.log(err); //nothing here!
        });
    });

    connection.connect(params);
```

All commands tested from my terminal over telnet successfully, they just don't work with this module.

Am I doing something wrong?

**Comment by mkozjak** [comment]
Hi, @ericuldall. Are you sure the prompt is an empty string? What strings do you get after connecting with 'telnet'?

For 'debug' it's normal that there's no debug messages. It's in my todo list.

**Comment by ericuldall** [comment]
The line my cursor starts on when I telnet in is an empty line. No prompt is shown.

**Comment by ericuldall** [comment]
I've added a log line to parseData and I can see that my exec command is getting sent and for some reason the responseready event is not ever emitted.

```
190 function parseData(chunk, telnetObj, callback) {
191   console.log(chunk.toString()); //this returns the proper response from remote
```

**Comment by ericuldall** [comment]
looks like it's getting caught here:

```
234   else if (telnetObj.telnetState === 'response') {
235     var stringData = chunk.toString()
236 
237     telnetObj.stringData += stringData
238     promptIndex = stringData.indexOf(telnetObj.shellPrompt)
239 
240     if (promptIndex === -1 && stringData.length !== 0) {
241       if (search(stringData, telnetObj.pageSeparator) !== -1) {
242         telnetObj.telnetSocket.write(Buffer('20', 'hex'))
243       }
244 
245         console.log('got here');
246       return
247     }
```

**Comment by ericuldall** [comment]
When I add the following lines it works:

```
233   else if (telnetObj.telnetState === 'response') {
234     var stringData = chunk.toString()
235     telnetObj.stringData += stringData
236     promptIndex = stringData.indexOf(telnetObj.shellPrompt)
237     if (promptIndex === -1 && stringData.length !== 0) {
238       if (search(stringData, telnetObj.pageSeparator) !== -1) {
239         telnetObj.telnetSocket.write(Buffer('20', 'hex'))
240       }
241       telnetObj.cmdOutput = telnetObj.stringData.split(telnetObj.irs); //added cmd split
242       telnetObj.emit('responseready'); //emit response ready
243       return
244     }
```

**Comment by mkozjak** [comment]
@ericuldall, is there any chance I could get access to that device? Is it a known operating system or a custom one?

I'd like to debug this with the real thing. :)

**Comment by ericuldall** [comment]
I'm testing on publicly accessible mx servers.

Gmail:
[ { exchange: 'alt4.gmail-smtp-in.l.google.com', priority: 40 },
  { exchange: 'alt2.gmail-smtp-in.l.google.com', priority: 20 },
  { exchange: 'gmail-smtp-in.l.google.com', priority: 5 },
  { exchange: 'alt1.gmail-smtp-in.l.google.com', priority: 10 },
  { exchange: 'alt3.gmail-smtp-in.l.google.com', priority: 30 } ]

Hotmail:
[ { exchange: 'mx3.hotmail.com', priority: 5 },
  { exchange: 'mx2.hotmail.com', priority: 5 },
  { exchange: 'mx1.hotmail.com', priority: 5 },
  { exchange: 'mx4.hotmail.com', priority: 5 } ]

**Comment by mkozjak** [comment]
@ericuldall, aah, you can use the ```negotiationMandatory``` option and set it to ```false```.

A working example:
```js
var telnet = require('telnet-client');
var connection = new telnet();

var params = {
  host: 'alt3.gmail-smtp-in.l.google.com',
  port: 25,
  timeout: 1500,
  negotiationMandatory: false,
  ors: '\r\n', // mandatory for your 'send' to work
  waitfor: '\n' // mandatory for your 'send' to work (set those either here or in your exec_params!)
};

connection.on('connect', function() {
  connection.send('first message', function(err, res) {
    if (err) return err

    console.log('first message:', res.trim())

    connection.send('HELO hi', {
      ors: '\r\n',
      waitfor: '\n'
    }, function(err, res) {
      if (err) return err

      console.log('resp after cmd:', res)
    })
  })
})

connection.connect(params)
```

Also see https://github.com/mkozjak/node-telnet-client/blob/8992602190a0cf5588d88422c7fac739b64e9f56/test/004_negotiation_optional.js#L28

Basically, you need to send something if there's no prompt to match.

This is a case similar to this one: https://github.com/mkozjak/node-telnet-client/issues/30

That's why I implemented a ```send``` command. Hope it helps!!

**Comment by ericuldall** [comment]
This kind of works...at least well enough for my needs. The only problem is the responses are always one command behind. Is this the expected behavior?

**Comment by mkozjak** [comment]
Yeah, send works like a simple tcp server. Nothing smart behind it. If we do not have any prompts, that is the only way to get through this scenario. 

Btw, I get that second message from the server after sending HELO hi. Seems like that is the order...?

**Comment by ericuldall** [comment]
I think the order is off:

```
connection.send('HELO hi', function(res){ 
//here res returns the initial connection response
//expected: 250 mx.google.com at your service
//actually got: 220 mx.google.com ESMTP r3si20876455wjl.28 - gsmtp
});

**Comment by mkozjak** [comment]
You need to send an initial message before it. You cannot receive data before sending it out. 
'first message' is the initial one. 

Then I sent another one, 'HELO hi', and received the 220 message.

**Comment by ericuldall** [comment]
That's because the response from 'first message' is the same as the response from 'HELO hi'

**Comment by mkozjak** [comment]
Am I missing something?

Response from 'first message':
```
220 mx.google.com ESMTP i65si25783123pfb.183 - gsmtp
```

Response from 'HELO hi':
```
250 mx.google.com at your service
```

**Comment by ericuldall** [comment]
Yes, you are missing something.

```
220 mx.google.com ESMTP i65si25783123pfb.183 - gsmtp
```

That is the response shown when you first connect to the server. It's not the result of 'first message'

**Comment by mkozjak** [comment]
But you cannot receive data before first sending some data over. You're not having any prompts, and that's a _must_ for telnet. So you need to 'initiate' the data flow. That's how ```send``` behaves. There's no other way.

**Comment by ericuldall** [comment]
I understand it's a limitation of the way this works. I have it working well enough for my needs. It's just worth noting the responses are always 1 command behind. Maybe you should send an empty message automatically to get the responses to sync up with the cmd issued.

**Comment by mkozjak** [comment]
It's definitely an interesting suggestion. I will need to evaluate this and see how other more popular telnet libraries approach to solving this problem (ie. perl's Net::Telnet). Cheers!
