### ISSUE TITLE
Heap out of memory problem with send

### ISSUE THREAD

**Issue by chipp972** [mkozjak/node-telnet-client#47]
Hi,

I think there is a little problem in the send function since when I execute 1000+ send the node process grows untill it takes 72.5% of the total memory (2Gb) then it stops brutally and throws the message :

> <--- Last few GCs --->
> 
>    96266 ms: Scavenge 1389.0 (1435.0) -> 1389.0 (1435.0) MB, 10.5 / 0 ms (+ 0.7 ms in 2 steps since last GC) [allocation failure].
>    96272 ms: Scavenge 1389.0 (1435.0) -> 1389.0 (1435.0) MB, 5.9 / 0 ms [allocation failure].
>    97397 ms: Mark-sweep 1389.0 (1435.0) -> 1389.0 (1435.0) MB, 1124.4 / 0 ms (+ 0.7 ms in 2 steps since start of marking, biggest step 0.6 ms) [last resort gc].
>    98514 ms: Mark-sweep 1389.0 (1435.0) -> 1389.0 (1435.0) MB, 1116.9 / 0 ms [last resort gc].
> 
> <--- JS stacktrace --->
> 
> ==== JS stack trace =========================================
> 
> Security context: 0x1903ba4c9fa9 <JS Object>
>     1: /\* anonymous */ [/myProject/node_modules/telnet-client/lib/telnet-client.js:~150] [pc=0x398970b8a8d8](this=0x2e82ee0a1659 <a Telnet with map 0x12afcc0759b9>,data=0x30aabc1453f1 <an Uint8Array with map 0x12afcc005441)
>     2: emitOne(aka emitOne) [events.js:~94] [pc=0x398970b7a6bb] (this=0x1903ba404189 <undefined>,handler=0x3994910804e9 <JS Array[4282]>,isFn=0...
> 
> FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
> Aborted (core dumped)

If I change the line 150 from `self.on('data', function(data) {` to `self.once('data', function(data) {` my script works fine.

**Comment by mkozjak** [comment]
Well, you can't just listen on only the first 'data' event, since you'll lose all other data chunks if they arrive separately later. I'll test this one and report back!!

**Comment by chipp972** [comment]
Here is my code:
```
'use strict'
const Telnet = require('telnet-client')
let resultpath = './logs.txt'
let saveStream = fs.createWriteStream(resultpath, {'flags': 'a'})

let params = {
  host: '10.1.2.3',
  port: 23,
  shellPrompt: /Blabla[\s\S]*%/,
  loginPrompt: /user[\s\S]*/,
  passwordPrompt: /[\s\S]*pass[\s\S]*/,
  timeout: 3000,
  username: 'admin',
  password: 'pass',
  irs: '\r\n',
  ors: '\r'
}

function execCommands (cmdList, params) {
  let session = new Telnet()
  let count = 0
  
  session.once('ready', () => {
    for (let cmd of cmdList) {
      session.send(cmd, params, (err, response) => {
        if (err) { console.log(err) }
      })
    }
  })

  session.on('data', (data) => {
    let info = /someRegexp/ig.exec(data)
    if (info) {
      count++
      process.stdout.clearLine()  // clear current text
      process.stdout.cursorTo(0)  // move cursor to beginning of line
      process.stdout.write(`Info found: ${count}`)
      saveStream.write(info[1] + '\n')
    }
  })

  session.on('timeout', () => {
    console.log('timeout')
    session.end()
  })

  session.on('error', (err) => {
    console.log(err)
    session.end()
  })

  session.on('close', () => {
    console.log('closing connection')
  })

  session.on('end', () => {
    console.log('\nend of the script')
    saveStream.end()
  })

  session.connect(params)
  session.setMaxListeners(0) // because session.send() add a listener
}

// I build a list of commands from a database connection etc.
let commands = buildCommands()
execCommands(commands, params)
```
Each command is answered with some data and I manage to retrieve all data logged in my file (logs.txt).
I listen to all the data event in my code but it's only one listener. In the send function code, each send create a listener that listen to all data event that's why it takes so much memory when executing 1000 sends I think.

**Comment by mkozjak** [comment]
@chipp972: What happens if you put ```self.removeListener('data')``` on lines 155 and 163?

**Comment by mkozjak** [comment]
@chipp972: Any news?

**Comment by Codelica** [comment]
Ran into this recently.  Didn't have much time to dig into the code, but pretty sure this is due to the send() function including self.on('data') which will register a new event listener every send() call.   Like  in my case I'm sending a command to OpenVPN every 2 seconds and gathering reply.  After the first 10 or so I'd get:

(node:21325) Warning: Possible EventEmitter memory leak detected. 11 data listeners added. Use emitter.setMaxListeners() to increase limit

Tossing something in my code I could see that 'data' event increases it's listener count with every telnet send() event.

**Comment by mkozjak** [comment]
Should implement different logic for .send(). Looking into it.

**Comment by ErAz7** [comment]
still not fixed after 7 years!
is this repo maintained? I was running into a production crash because of this
