### ISSUE TITLE
Can I take out all the returned information but not only command's reply

### ISSUE THREAD

**Issue by QingxianZhu** [mkozjak/node-telnet-client#48]
I am currenty trying to make a telnet into a switch.
I want to get all the response from server。
What should I do to solve this problem? looking forward to your reply
The code part i used is:

var telnet = require('telnet-client');
var connection = new telnet();
  var params = {
    host: "172.18.190.11",
    port: 23,
    shellPrompt: " >",
    //timeout: 3000,
    username: "",
    password: "",
    loginPrompt: "admin",
    passwordPrompt: "admin",
    stripShellPrompt: false,
    negotiationMandatory: false
  };

  connection.on('ready', function (prompt) {
    connection.exec(script, function (err, response) {
      console.log(response);
      connection.destroy();
    });
  });

  connection.on('timeout', function () {
    connection.end();
  });

  connection.on('close', function () {
    console.log("connection closed");
  });

  connection.connect(params);

**Comment by mkozjak** [comment]
@QingxianZhu: If you use ```negotiationMandatory: false``` then you should use the ```send``` method. That way you might be able to get all the data. Something along these lines:

```js
var t = require('telnet-client')
var c = new t()

var params = {
  host: '127.0.0.1',
  port: 8080,
  negotiationMandatory: false
}

c.on('failedlogin', function() {
  console.log('login failed')
})

// callback...
c.on('connect', function() {
  console.log('sending data')

  c.send('something', {
    ors: '\r\n',
    waitfor: '\n'
  }, function(error, data) {
    console.log('received a response', data)
  })
})

// ...or promise
c.connect(params)
.then(function() {
  c.send('something', {
    ors: '\r\n',
    waitfor: '\n'
  }, function(error, data) {
    console.log('received a response:', error, data)
  })
})

```

**Comment by QingxianZhu** [comment]
ow ow, but when i try to connect switch using an incorrect user or password, no event has been triggered, so it was hang up. What should I do to get this error?
var telnet = require('telnet-client');
var connection = new telnet();
var params = {
host: "172.18.190.11",
port: 23,
shellPrompt: " >",
//timeout: 3000,
username: "",
password: "",
loginPrompt: "admin",
passwordPrompt: "admin",
stripShellPrompt: false
};

connection.on('ready', function (prompt) {
connection.exec(script, function (err, response) {
console.log(response);
connection.destroy();
});
});

connection.on('timeout', function () {
connection.end();
});

connection.on('failedlogin', function () {
connection.end();
});

connection.on('error', function () {
connection.end();
});
connection.on('close', function () {
console.log("connection closed");
});

connection.connect(params);

**Comment by mkozjak** [comment]
@QingxianZhu: use the ```failedLoginMatch``` options. Consult documentation for further details.
