### ISSUE TITLE
`exec` doesn't work if it sends too much data at once

### ISSUE THREAD

**Issue by barak-shirali** [mkozjak/node-telnet-client#51]
I am sending around 1KB of data at exec and it doesn't run without error.

**Comment by mkozjak** [comment]
I'll need more information than that. Your code example and errors.

**Comment by barak-shirali** [comment]
Thanks for yoru response @mkozjak .
It's generic `connection.exec` call to avaya G3 telnet server.

```
connectionParams = {
host: XXX,
port: XXX,
timeout: XXX,
username: XXX
password: XXX,
shellPrompt: XXX,
stripShellPrompt: false,
ors: '\r\n',
irs: '\n'
};

cmd = 'a long command';

connection.exec(cmd)
```

if `cmd` is badly formatted, I usually get error, otherwise, it runs without error.
When I send long command, it doesn't occur error which means it is successful. However when I looking for changes with other command, it is not made.
Short commands like 30~50 bytes, is always successful. 

When I try running app on worse latency client, it is successful. so I assume it is about too much data is sent at once.

I tried to send command manually by chunks with multiple `exec` with long timeout, and 50ms delay between chunks. (the command is run only with certain special character which is sent at last.). However I can see that each `exec` is creating an event listener and waiting for response. Same for `send`.

Do you think we can send long data by chunks on `exec`? I think we could have a config like terminal speed which is used to split long data into pieces.

**Comment by mkozjak** [comment]
@barak-shirali: I have managed to send 100KB of data with ```exec``` and have received a response.
Can you tell me what the error looks like? Can you get a normal response with a linux ```telnet``` command?

**Comment by barak-shirali** [comment]
@mkozjak I think it could be telnet server side problem. The server could not be ready for high volume of data in short amount of time.

The response from the telnet server is quite hacky, in case of error it returns with a letter `e` and error code. But I don't get error at this time.

And yes, I had problem with linux telnet problem once(not always). Same result, but not run properly on server.

**Comment by barak-shirali** [comment]
@mkozjak I ended up adding a pure send function which doesn't wait for response.
and added manual delay between each chunk to make it work.

```
Telnet.prototype.sendChunk = function(cmd, opts) {
    var self = this
    if (opts && opts instanceof Object) {
        self.ors = opts.ors || slef.ors
    }

    cmd += self.ors

    if (self.telnetSocket.writable) {
        self.telnetSocket.write(cmd)
    }
}
```

```
cmdLines = command.split('\n')
_.reduce(cmdLines, function(promise, cmd) {
  connection.sendChunk(cmd)
  q.delay(100)
}, q.resolve())
```

**Comment by barak-shirali** [comment]
Perhaps this kind of function could give us more lower level control.

**Comment by mkozjak** [comment]
@barak-shirali: I believe you could implement a new [net](https://nodejs.org/api/net.html) server without this library, then.
