### ISSUE TITLE
Can't connect to Telnet: gives ECONNREFUSED error

### ISSUE THREAD

**Issue by adamboazbecker** [mkozjak/node-telnet-client#52]
I've been trying to connect to Telnet but for some reason I can't make the initial connection.

I essentially **copied and pasted** the code from the example. It looks like this:

    var telnet = require('telnet-client');
    var connection = new telnet();

    var params = {
        host: '127.0.0.1',
        port: 23,
        shellPrompt: '/ # ',
        timeout: 1500
    };

    connection.connect(params);

But when I compile the code, I keep getting **this error**:

    events.js:141
          throw er; // Unhandled 'error' event
          ^

    Error: connect ECONNREFUSED 127.0.0.1:23
        at Object.exports._errnoException (util.js:870:11)
        at exports._exceptionWithHostPort (util.js:893:20)
        at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1057:14)

Does anyone know what's going on?

**Comment by mkozjak** [comment]
First of all, try connecting to your server with unix' telnet command (if you're on unix). Also try sniffing for the port 23 with netstat -tupane | grep 23 and see if anything is listening there. Also, your prompt is most probably wrong.

**Comment by adamboazbecker** [comment]
Thank you mkozjak. 

Even though I was able to telnet using the `telnet` command, I wasn't able to do it via the module. Here is what I did on my Mac:

    telnet gmail-smtp-in.l.google.com 25

And I got this response:

    Trying 2607:f8b0:4003:c09::1a...
    Connected to gmail-smtp-in.l.google.com.
    Escape character is '^]'.
    220 mx.google.com ESMTP k44si17042964otk.63 - gsmtp

Which is what I was looking for. When I played around with the module, however, I wasn't able to get it there. Here is what I did:

    var telnet = require('telnet-client');
    var connection = new telnet();

    var params = {
        host: 'gmail-smtp-in.l.google.com',
        port: 25, //I tried different ports
        shellPrompt: ' ', //I tried different shellPrompts. Should I look for it somewhere?
        timeout: 2500
    };
    
    connection.on('timeout', function() {
        console.log('socket timeout!');
        connection.end();
    });
    
    connection.on('close', function() {
        console.log('connection closed');
    });
    
    connection.connect(params);
    
    connection.on('ready', function(prompt) {    
        console.log('hooray!'); //I never see this
    });

Instead of finding what I was looking for, I simply get `socket timeout`.

Should I be looking for the `shellPrompt` or the `port` elsewhere?

**Comment by mkozjak** [comment]
Seems like you're trying to do a similar thing like in this ticket: https://github.com/mkozjak/node-telnet-client/issues/46#issuecomment-220246558

Check all of the dialog, also. If you'd need an initial message (#49), please, let me know and I'll try to resolve that one.

**Comment by adamboazbecker** [comment]
Thank you mkozjak. That's a great response and solves the issue.
