### ISSUE TITLE
Options for connection.send() aren't optional

### ISSUE THREAD

**Issue by ashwinvandijk** [mkozjak/node-telnet-client#58]
The options for `connection.send()` should be optional, but when omitted, an error is returned:

    if (opts.waitfor === undefined) {
                ^

    TypeError: Cannot read property 'waitfor' of undefined
        at /Users/Ashwin/Sites/SnapControl/node_modules/telnet-client/lib/index.js:161:17

A solution for now is to always pass an empty object:

    connection.send(cmd, {})
        .then(function(res) {
            console.log('promises result:', res)
        })

Is this by design? I would be happy to file a simple pull-request for this if not.

**Comment by mkozjak** [comment]
@ashwinvandijk: Thanks for reporting this! It's now fixed and available on npm!

**Comment by ashwinvandijk** [comment]
Unfortunately it still isn't working as expected. Passing {} should be the same as passing nothing. My request works when passing {}, but if I don't pass anything it doesn't return anything. Didn't have time to look into it much further that this...

**Comment by mkozjak** [comment]
@ashwinvandijk: I'm so sorry for a problem, it's fixed now!
