### ISSUE TITLE
Read only once/Read only relevant response for a Send command

### ISSUE THREAD

**Issue by NischalBomdika** [mkozjak/node-telnet-client#59]
I'm using a Telnet device with no prompt on it. So i believe i need to use Send() and negationationMandatory: false as described in Issue #46 

Send() doesn't seem to pair Requests and Responses together properly while Exec() does. 

I've noticed that when i subscribe to the data event and also try to read the response from a Send command - the same response is read twice - once in data event and once in response. This may be similar to Issue #8 
Is it possible to read only once in the Send() just as in the fix above?

**Comment by mkozjak** [comment]
Can you show me your code snippet? Why are you listening on the event and using the response callback at the same time?

**Comment by NischalBomdika** [comment]
Yes, i am listening to the data events for device notifications, and also trying to read the callback on the request.

// Connection establishment and Event subscription;
function initializeTelnetConnection(){
connection.on('connect', function() {
    sendInitialCommands();
  });

  connection.on('timeout', function() {
    connection.end();
    connection.connect(params);
  });

  connection.on('close', function() {
  });

  connection.on('end', function() {   
  });

  connection.on('data', function(data) {
    if (JSON.parse(data).status === "NOTIFICATION")
    {
      deviceNotificationReceived(data);
    }
    else
    {      
      // ignore
    }
  });

  connection.connect(params);
};




// Code for the Send command - to read response on request
function sendCommand(cmd, callback) {
    connection.send(cmd, {
      ors: '\r\n',
      waitfor: '\n'
      }, function(err, res) {
        if (err) {
            return callback("error", res);
        }
          return callback(null, res);
});

**Comment by mkozjak** [comment]
Aah, yes. As the documentation says, a ```data``` event is "a forwarded ```data``` event from core 'net' library". That means you'll get all the relevant and/or irelevant data there.

As per the response order.. That's why we have ```exec```. Using ```send``` is just a convenience method for a pure ```socket.write``` and an instant receive of whichever data was received in whatever order. We cannot assume any order, since we are not using any telnet negotiation logic.

I believe you could accomplish your task without using this library, since you don't really need telnet, if you're only using ```send```.

**Comment by NischalBomdika** [comment]
Thank you for the response. 

However, i'm still wondering if there is anything i can do in this situation to fix the issue i'm having. With no prompt on the device (negotiationMandatory = false), i believe i cannot use the Exec method. With send(), i cannot achieve my target due to the above stated reasons.

Two options i want to explore:

Option 1) Can we fix the multiple reads with send/data event such that if the data is read once (either in data event or send callback), it's not read again (through the other methods)?

Option 2) Can i somehow use the Exec method in spite of not having a prompt on the telnet?

**Comment by mkozjak** [comment]
Yes, I'd go for the first option!

Once you subscribe to the ```data``` event only once, that very listener will be removed once the first event is hit.
