### ISSUE TITLE
execTimeout parameter seems to hold the connection open

### ISSUE THREAD

**Issue by pghalliday** [mkozjak/node-telnet-client#60]
I have some code that goes like this:

```javascript
const co = require('co');
const Client = require('telnet-client');

co(function * () {
  const client  = new Client();
  yield client.connect({
    host: '192.168.2.2',
    port: 23
  });
  const output = yield client.exec('pwd', {
    execTimeout: 10000
  });
  console.log(output);
  yield client.end();
  console.log('end');
});
```

And I have noticed that even though the `pwd` command completes immediately and the `console.log` prints the output and `end` message immediately, the script always takes another 10 seconds to exit. It's as if the `client.end()` call does nothing and it's waiting for the `execTimeout`.

I also tried with `client.destroy()` but it made no difference.

**Comment by pghalliday** [comment]
I notice in the `end` and `destroy` methods the promises are resolved immediately whatever happens and don't really wait.

**Comment by pghalliday** [comment]
Gah, it's because you don't cancel the timeout!

Pull request imminent ;)

**Comment by mkozjak** [comment]
Yup, just realized. Been debugging. ;)

PR, yup! :D

**Comment by pghalliday** [comment]
ok I have done, thanks :)

**Comment by mkozjak** [comment]
Nice, thank you!
