### ISSUE TITLE
Endless loop on login

### ISSUE THREAD

**Issue by kaYcee** [mkozjak/node-telnet-client#65]
Thanks for the very useful package. I must access a telnet server that shows no error on wrong credentials but instead shows the login prompt again. Unfortunately, this leads to an endless trial of login attempts and the promise never resolves. Providing the `failedLoginMatch` parameter with the value `login:`  won't work as this parameter seems to get checked before the actual `loginPrompt` variable. Any idea how to solve that? Thx!

**Comment by mkozjak** [comment]
@kaYcee: Thanks for reporting this issue! I've been looking into a possible solution. Currently, I'm all over the place regarding free time, but I will try solving the issue as soon as possible.
You can also try hacking around the library and issuing a PR if you find a solution!
