### ISSUE TITLE
Very long string caused GC fails to allocate memory

### ISSUE THREAD

**Issue by wfadam** [mkozjak/node-telnet-client#67]
I'm using telnet-client@0.10.7 on a 32-bit CentOS 5.6 without changing the --max-old-space-size flag of node.
A comand line 'tail -f some-files' is invoked via this module on remote machines. I'm trying to stream the text content from multiple files as long as possible. After serveral hunderds of MB are received, this error occurs.

Looks the module is trying to find a shell prompt regardless the incoming string size.

<--- Last few GCs --->

 5394881 ms: Mark-sweep 680.6 (702.0) -> 668.1 (689.5) MB, 11.2 / 0.0 ms [allocation failure] [GC in old space requested].
 5394894 ms: Mark-sweep 668.1 (689.5) -> 668.1 (689.5) MB, 12.7 / 0.0 ms [allocation failure] [GC in old space requested].
 5394906 ms: Mark-sweep 668.1 (689.5) -> 668.1 (674.5) MB, 12.5 / 0.0 ms [last resort gc].
 5394917 ms: Mark-sweep 668.1 (674.5) -> 668.1 (674.5) MB, 10.4 / 0.0 ms [last resort gc].

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0xb577b815 <JS Object>
    1: indexOf [native string.js:~68] [pc=0x3376f0e5] (this=0x573f5a55 <Very long string[28968511]>,z=0x573a34f1 <String[2]: $ >,A=0xb57081d9 <undefined>)
    2: arguments adaptor frame: 1->2
    3: parseData [/home/node_modules/telnet-client/lib/telnet-client.js:~196] [pc=0x3377bc5a] (this=0xb578a069 <JS Global Object>,chunk=0x573f59d9 <an Uint8Array with map 0x43738251>,telnetObj=0x458...

**Comment by mkozjak** [comment]
Might be related to #11. Gonna investigate.

**Comment by mkozjak** [comment]
We should implement a 'streaming' feature where we would check if the prompt didn't appear for a timeout (or max memory per process is reached) and print out available data (resolve).
Resolved data should then be erased from memory.

**Comment by mkozjak** [comment]
@wfadam Are you using ```exec``` or ```send```?

**Comment by mkozjak** [comment]
The crash has been fixed with the latest release.
The streaming API you'd like to see is yet to be implemented, though.

**Comment by mkozjak** [comment]
@wfadam: Streaming api is now implemented. Forgot to address you, sorry!
