### ISSUE TITLE
Support polling

### ISSUE THREAD

**Issue by sanderd17** [mkozjak/node-telnet-client#70]
I'd like to poll a device using telnet, but it's not entirely clear what's the best way to do this.

For the moment I'm experimenting with this code
```js
connection.on('ready', function(prompt) {
  console.log("ready");
  setInterval(() => connection.exec("rfid:qid.id", (err, res) => console.log(res)), 1000);
});
```
But after 10 requests, I get the warning 
`(node:12588) Warning: Possible EventEmitter memory leak detected. 11 bufferexceeded listeners added. Use emitter.setMaxListeners() to increase limit`

Is there a better (supported) way to implement polling?

**Comment by mkozjak** [comment]
Hi!

Seems like the device is not responding and the listeners for the ```bufferexceeded ``` are left lingering.

Please, try using the execTimeout option and see if it helps.
We should generally also implement a cancellation API, since promises are used.

**Comment by sanderd17** [comment]
I do get responses back (it logs a line every second).  
Setting the execTimeout to 5s or 1s didn't fix the problem. (setting it to 5s makes the first response to be a complete console output with multiple commands for some reason)

Perhaps it may also be related to #11 , as I've found that sometimes characters from the prompt are gone. Then again, to solve that I select anything that looks like /.*>/ (normally the prompt is "RF IDeas>", bot often shows as "RFIDes>", "RF Dea>", ...)

**Comment by mkozjak** [comment]
Yes, I probably have a bug. Real busy at the moment, but will look into it asap. Thanks!

**Comment by sanderd17** [comment]
I don't expect free support within a minute, I'm already happy you're willing to take a look ;)

But it's also likely there are issues with the telnet server. It's an RFID tag reader over ethernet, and the console behaves a bit strange. Like I sometimes don't get a prompt when I connect, and I don't even see any characters, untill I press enter. Though it does register the characters I type, as I get replies for those commands when pressing enter.

**Comment by sanderd17** [comment]
Heh, now I got a run where the first responses are a bit chewed up too.

Here I logged `err + " RES " + res + " END RES"`, the error is null every time, but the response should be `{0xFFFF,0,0x00,0;0x00}` every time, as there wasn't a card present on the reader. The first answers however are a bit messed up before it stabilizes.

```
ready
null RES K}RF Dea
{Error#4}

 END RES
null RES {xFFF,0,x000;000}
 END RES
null RES xFF,00x00;00}

 END RES
null RES xFF,00x00;00}

 END RES
null RES xFF,0x00;00}
 END RES
null RES xFFFF,0,0x00,0;0x00}

 END RES
null RES {0xFFFF,0,0x00,0;0x00}

 END RES
null RES {0xFFFF,0,0x00,0;0x00}

 END RES
null RES {0xFFFF,0,0x00,0;0x00}

 END RES
null RES {0xFFFF,0,0x00,0;0x00}

 END RES
(node:2216) Warning: Possible EventEmitter memory leak detected. 11 bufferexceeded listeners added. Use emitter.setMaxListeners() to increase limit
null RES {0xFFFF,0,0x00,0;0x00}

 END RES
```

**Comment by mkozjak** [comment]
@sanderd17 is there a way for you to send me a full capture (tcpdump) of some session reproducing the issue? Would drastically ease the debugging.

Also, I'd need your shellPrompt setting.

**Comment by sanderd17** [comment]
I'm using Windows PowerShell with the default settings (apart from color theme).

And I'm sending the tcpdump to your email. Although I tried to close anything network related, I don't like to publish all communication from my computer on the internet.

**Comment by sanderd17** [comment]
We've decided to go via the ethernet ip protocol instead of telnet.

So it's no longer neccesary for us that these problems are fixed, but if you want, I can still test some stuff on these devices for you.

**Comment by mkozjak** [comment]
Sorry for not responding!

The problem was with the dump 'cause I failed to find the corresponding packets.
But, yeah, please send me a dump only of port 23 (if that's the port your telnet server is running on!)

tcpdump -i <int> port 23...

**Comment by sanderd17** [comment]
I'm using Windump on Windows, and didn't realise there was a port filter. As the file is smaller now, and only contains quite safe traffic, I can share it here ...

In this file, the first run failed, and the second succeeded.

It's using port 10001 btw, port 23 is reserved for the telnet server on the device to set basic parameters (fixed ip address, port of the main telnet server, ...)

[diagTraces0.txt](https://github.com/mkozjak/node-telnet-client/files/698452/diagTraces0.txt)

**Comment by mkozjak** [comment]
Seems like it works only when using prompt ```RF IDeas>```. But, yeah, the server really behaves strangely here. Will look into it further, thanks!
