### ISSUE TITLE
TypeError: this.buffers[pos.buf].get is not a function

### ISSUE THREAD

**Issue by mukulJainSuccessive** [mkozjak/node-telnet-client#71]
I used same code from official docs of this package (no change at all) and then I go in my telnet shell and enter command 
```
open localhost
```

It gave following error and crashed out of telnet shell.

```
/home/~/node_modules/buffers/index.js:185
    return this.buffers[pos.buf].get(pos.offset);
                                 ^

TypeError: this.buffers[pos.buf].get is not a function
    at Buffers.get (/home/~/node_modules/buffers/index.js:185:34)
    at parse (/home/~/node_modules/telnet/lib/telnet.js:145:15)
    at Socket.<anonymous> (/home/~/node_modules/telnet/lib/telnet.js:201:11)
```

**Comment by mkozjak** [comment]
Which version of library are you using? I strongly suggest you try the latest. Since there is a filename called 'telnet.js', I suppose this is a somewhat outdated version.

Also, the crash comes from the 'buffers' library.
