### ISSUE TITLE
Interactive shell session

### ISSUE THREAD

**Issue by vikasgoswami** [mkozjak/node-telnet-client#72]
Can we create interactive shell session using this module, same as .shell method from ssh2 module. 
Please help

**Comment by mkozjak** [comment]
There's no support for it, currently. Should implement this! Thanks for the idea.

**Comment by vikasgoswami** [comment]
Thanks for your quick response.

Can we achieve same like of functionality using exec or send method from this module?

**Comment by mkozjak** [comment]
Yes, you should print out your strings you're sending through exec/send methods and all the responses that come out. Unfortunately, you cannot replicate the looks of the entire console session.

I'll try implementing the streaming feature soon enough!

**Comment by vikasgoswami** [comment]
Do you have any idea about any other module which can support streaming feature for telnet? I have searched, I didn't found such kind of module.
Please help.

**Comment by mkozjak** [comment]
Nope. I'm in the process of implementing it if you can wait for a few more days...

**Comment by mkozjak** [comment]
@vikasgoswami: Try version 0.13.0. Start a stream and use it like normal:
```js
...
connection.shell(function(error, stream) {
    stream.on('data', (data) => console.log(data.toString()))

    setTimeout(() => stream.write('uptime\n'), 100)
    setTimeout(() => stream.write('df\n'), 200)
})
...
```

**Comment by vikasgoswami** [comment]
Thank You for your help.
