### ISSUE TITLE
Unexpected token =>, tests failing

### ISSUE THREAD

**Issue by vikasgoswami** [mkozjak/node-telnet-client#73]
I am using telnet-client module version : 0.13.0. My node version is : 6.9.4.

After creating build using "gulp build" command, and opening executable build file, I am getting below error : 

client\lib\index.js:18
    return new Promise(resolve => {
                               ^^
Unexpected token =>

Could you please let me know, where is my mistake.

It is working fine, if I am using same application from web.

**Comment by mkozjak** [comment]
@vikasgoswami: Can you give me an output of this? (change /path/to/node_modules to your app's root dir)
```js
node -v && cd node_modules/telnet-client && npm it
```

**Comment by vikasgoswami** [comment]
> nodeunit test


001_generic
✖ generic - connect

Assertion Message: Client did connect
AssertionError: false == true
    at Object.ok (\node_modules\telnet-client\node_modules\nodeunit\lib\types.js:83:39)
    at Telnet.<anonymous> (\node_modules\telnet-client\test\001_generic.js:37:12)
    at emitNone (events.js:86:13)
    at Telnet.emit (events.js:185:7)
    at Socket.<anonymous> \node_modules\telnet-client\lib\index.js:53:12)
    at Socket.g (events.js:291:16)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1074:10)


002_busybox
✔ busybox - exec_string_shellprompt
✔ busybox - exec_regex_shellprompt

003_server_push
✔ server_push - receive_pushed_data

004_negotiation_optional
✔ negotiation_optional - send_data
✔ negotiation_optional - send_data_without_options
✔ negotiation_optional - send_data_without_options_promise

FAILURES: 1/7 assertions failed (4346ms)
npm ERR! Test failed.  See above for more details.

**Comment by vikasgoswami** [comment]
v6.9.4

**Comment by vikasgoswami** [comment]
Which minimum version of node required to use this module?

**Comment by vikasgoswami** [comment]
This is the response from second machine:

001_generic
? generic - connect

Assertion Message: Client did connect
AssertionError: false == true
    at Object.ok (\node_modules\telnet-client\nodeunit\lib\types.js:83:39)
    at Telnet.<anonymous> (\001_generic.js:37:12)
    at emitNone (events.js:86:13)
    at Telnet.emit (events.js:185:7)
    at Socket.socket.net.createConnection (\node_modules\telnet-client\lib\index.js:52:14)
    at Socket.g (events.js:291:16)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1074:10)


002_busybox
? busybox - exec_string_shellprompt
? busybox - exec_regex_shellprompt

003_server_push
? server_push - receive_pushed_data

004_negotiation_optional
? negotiation_optional - send_data
? negotiation_optional - send_data_without_options
? negotiation_optional - send_data_without_options_promise

005_login
? login - ok
? login - fail

006_stress
? stress - buffer_exceeded

AssertionError: 2110080 === 2100000
    at Object.strictEqual (\node_modules\nodeunit\lib\types.js:83:39)
    at \node_modules\tel
0:14
    at tryCatcher (\node_modules\bluebird\js\release\util.js:16:23)
    at Promise.successAdapter [as _fulfillmentHandler0] (node_modules\telnet-client\node_modules\bluebird\js\release\nodeify.js:23:30)
    at Promise._settlePromise (\node_modules\bluebird\js\release\promise.js:564:21)
    at Promise._settlePromise0 (\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (\node_modules\bluebird\js\release\promise.js:691:18)
    at Async._drainQueue (\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)


007_streams
? streams - shell

FAILURES: 2/11 assertions failed (899ms)
npm ERR! Test failed.  See above for more details.

**Comment by vikasgoswami** [comment]
Please let me know if any more details required.

**Comment by vikasgoswami** [comment]
I am creating build by using below code:

var gulp = require('gulp')
var shell = require('gulp-shell')

var NodeWebkitBuilder = require('node-webkit-builder');

// Run project
gulp.task('run', shell.task([
    'node node_modules/node-webkit-builder/bin/nwbuild -v 0.12.3 -r ./'
]));

gulp.task('build', function(cb) {

    // Read package.json
    var package1 = require('./package.json')

    // Find out which modules to include
    var modules = []
    if (!!package1.dependencies) {
        modules = Object.keys(package1.dependencies)
            .filter(function(m) {
                return m != 'nodewebkit'
            })
            .map(function(m) {
                return './node_modules/' + m + '/**/*'
            });
    }

    // Which platforms should we build
    var platforms = []
    if (process.argv.indexOf('--win') > -1) platforms.push('win')
    if (process.argv.indexOf('--mac') > -1) platforms.push('osx')
    if (process.argv.indexOf('--linux32') > -1) platforms.push('linux32')
    if (process.argv.indexOf('--linux64') > -1) platforms.push('linux64')

    // Build for All platforms
    if (process.argv.indexOf('--all') > -1) platforms = ['win', 'osx', 'linux32', 'linux64']

    // If no platform where specified, determine current platform
    if (!platforms.length) {
        if (process.platform === 'darwin') platforms.push('osx')
        else if (process.platform === 'win32') platforms.push('win')
        else if (process.arch === 'ia32') platforms.push('linux32')
        else if (process.arch === 'x64') platforms.push('linux64')
    }

    // Initialize NodeWebkitBuilder
    var nw = new NodeWebkitBuilder({
        files: ['./package.json', './app/**/*'].concat(modules),
        cacheDir: './build/cache',
        platforms: platforms,
        version: '0.12.3',
        checkVersions: false
    })

    nw.on('log', function(msg) {
        // Ignore 'Zipping... messages
        if (msg.indexOf('Zipping') !== 0) console.log(msg);
    });

    // Build!
    nw.build(function(err) {

        if (!!err) {
            return console.error(err);
        }
        cb(err);
    })
});


As per my understanding, once we create build using "gulp build" command, at that time, it will not include the es6 supported files in the build package, and that's why we are getting an error. I tried with simple es6 script and facing same issue.

Could you please help me to find out the soulution.

Thanks!

**Comment by vikasgoswami** [comment]
Could you please help me to find out the solution for this problem? This issue is not related to this module, but if we have used any ES6 script in our code, and create build using "gulp build" command, and opening executable file, then it gives this error.

**Comment by vikasgoswami** [comment]
I have compiled latest version code and and converted into normal javascript using below script:

var gulp = require('gulp');
var babel = require('gulp-babel');

gulp.task('default', function () {

    return gulp.src('node_modules/telnet-client/**/*.js')
        .pipe(babel())
        .pipe(gulp.dest('dist'));
});

Will it work ?

**Comment by vikasgoswami** [comment]
getting undefined is not a function error while login from below index.js file:

if (this.socket.writable) this.socket.write(Buffer.from(negResp, 'hex'));

**Comment by vikasgoswami** [comment]
Please ignore all previous posts. I have compiled latest version code and integrating it with application.

Thanks for your help.

**Comment by FlowDirosa** [comment]
Hi,
I have same the problem.
TypeError: 'hex' is not a function (408 index.js)

Thanks for your help

**Comment by mkozjak** [comment]
@FlowDirosa which node version are you using?

**Comment by FlowDirosa** [comment]
I using v8.16.0
