### ISSUE TITLE
Login connection problem

### ISSUE THREAD

**Issue by vikasgoswami** [mkozjak/node-telnet-client#74]
```
var telnet = require('telnet-client');
var connection = new telnet();

var params = {
  host: '127.0.0.1',
  port: 23,
  shellPrompt: ' ',
 username: 'root',
password: 'root',
  timeout: 1500
};

connection.on('ready', function(prompt) {
  connection.exec(cmd, function(err, response) {
    console.log(response);
  });
});

connection.on('timeout', function() {
  console.log('socket timeout!')
  connection.end();
});

connection.on('close', function() {
  console.log('connection closed');
});

connection.connect(params);
```

1. Can we use username and password in the params object? I tried to use this way, but I am getting Login Incorrect error.

2. If connection is not successful, then connection.ready function should not be accessed. But from above code, it is accessible.

3. Connection is getting closed, after one command is executed.

4. I have used shell method inside connection.ready block. Is it correct?

5. I observed, whole function syntax is getting write on the terminal if we used send method before shell method. Could you please let me know, is there any mistake from my side?

**Comment by mkozjak** [comment]
@vikasgoswami Yes, you should set both loginPrompt and passwordPrompt parameters, also. Make sure shellPrompt is correct!

**Comment by vikasgoswami** [comment]
```
loginPrompt: "login: ",
passwordPrompt: "password:",
shellPrompt: ' ',
username: 'root',
password: 'guest'
```
Is this syntax correct?

If we pass username and password like this, then no need to use send command for them.. correct?

**Comment by vikasgoswami** [comment]
```


Sample Text

login:
```
I am getting this prompt once I opened putty... Could you please let me know what should be the shellPrompt for this?

**Comment by mkozjak** [comment]
Once you login with putty, you should see a shell prompt. 

This one is a login prompt.

**Comment by vikasgoswami** [comment]
Ok,

Why socket is getting timeout after command execution. Can we use multiple .shell method in single script?

**Comment by mkozjak** [comment]
if exec times out, it means the shell prompt didn't match in a defined time.
```.shell``` is designed to be used only one time in a single script.

**Comment by vikasgoswami** [comment]
I have used timeout: 5000 in params block and below is my code. I send multiple commands in stream.write, but after one or two commands, socket is getting timedout. Could you please help me for this.

```
stream.on('data', function(data) {
	
	if (data.indexOf('#') !== -1) {
		stream.write(cmd);
		stream.end();
	}
});
setTimeout(function(){ 
	stream.write(cmd1);
}, 1000);

setTimeout(function(){ 
	stream.write(cmd2);
}, 1000);

setTimeout(function(){ 
	stream.write(cmd3);
}, 1000);

setTimeout(function(){ 
	stream.write(cmd4);
}, 1000);

setTimeout(function(){ 
	stream.write(cmd5);
}, 1000);
```

**Comment by mkozjak** [comment]
Please also add an exception output.

**Comment by vikasgoswami** [comment]
I am getting the all commands in the stream.on('data') method, but only one or two commands are getting executed and then socket timeout.

**Comment by vikasgoswami** [comment]
It just gives socket timeout error.. Nothing else

**Comment by mkozjak** [comment]
I'll need to make a test case. Thanks for reporting.

**Comment by vikasgoswami** [comment]
Will it open three different terminal session, if I write three different commands in stream using .shell method?

**Comment by mkozjak** [comment]
It will use only one terminal.
