### ISSUE TITLE
Teamspeak 3 telnet issue

### ISSUE THREAD

**Issue by RonMelkhior** [mkozjak/node-telnet-client#78]
Hey,

Trying to implement the library into my own Teamspeak 3 query library.  
This is my code:

```javascript
// connection
this.socket = new telnet();
this.socket.connect({
    host,
    port,
    shellPrompt: '',
});

// on 'ready' event
this.socket.exec('help')
    .then(result => {
        console.log(result);
    })
    .catch(error => {
        console.log('Error!');
        console.log(error);
    });
```

For some reason, when I try to execute it, it fails and says `Error: response not received` even though it is.  
Also tried `waitfor: 'error'` (which is the end of each command response).

Example server: 91.121.83.227:10011

Why is it caused?

**Comment by mkozjak** [comment]
Hello, @RonMelkhior. The problem is in a shell prompt.
Seems like this telnet interface doesn't have any specific shell prompts as far as I've seen...
But, I see there's a line ```error id=0 msg=ok``` after every command is done. You could hook up to that one and build something like this:

```js
const telnet = require('telnet-client');

this.socket = new telnet();
this.socket.connect({
    host: 'hostname',
    port: port,
    shellPrompt: 'Welcome to the TeamSpeak 3 ServerQuery interface, type "help" for a list of commands and "help <command>" for information on a specific command.',
});

this.socket.on('ready', (prompt) => {
    this.socket.exec('help', {
        shellPrompt: 'error id=0 msg=ok'
    }, (error, response) => {
        if (error)
            throw new Error(error)

        console.log(response.toString())
    })  
})
```

You can set shell prompt on each ```exec``` call. An initial prompt would be: ```Welcome to the TeamSpeak 3 ServerQuery interface, type "help" for a list of commands and "help <command>" for information on a specific command.```

**Comment by RonMelkhior** [comment]
Ah alright, thanks for the help, much appreciated 👍
