### ISSUE TITLE
Block Scoped declarations not supported outside strict mode

### ISSUE THREAD

**Issue by starkmms** [mkozjak/node-telnet-client#79]
I have added telnet-client to my project but when i run it I get this message

![image](https://cloud.githubusercontent.com/assets/26894039/24646716/c20d254a-1914-11e7-9e93-2a85f9d93772.png)

you can remedy this by adding "use strict"; to the index.js file.

Am i missing something or is this something you would consider adding to the code

**Comment by mkozjak** [comment]
What node version are you using? This works for me with node 6.x

I have published the change, though. Thanks for reporting!

**Comment by starkmms** [comment]
4.4.5, so that probably explains it. Thanks for the speedy reponse

**Comment by mkozjak** [comment]
Aah, yes, we do not support 4.x anymore. :) (disclosure in readme)
