### ISSUE TITLE
promise not working

### ISSUE THREAD

**Issue by itsrajasekhar** [mkozjak/node-telnet-client#80]
Tried connecting to redis server which is installed locally on port 8000 with below snippet. The promise is never resolved. The version of telnet-client is latest 0.13.2 and node version is v6.3.0

```
var telnet = require('telnet-client');
var connection = new telnet();
 
var params = {
  host: '127.0.0.1',
  port: 8000,
  timeout: 1500
};
 
connection.connect(params)
.then(function(prompt) {
  connection.exec('info')
  .then(function(res) {
    console.log('promises result:', res)
  })
}, function(error) {
  console.log('promises reject:', error)
});
```

**Comment by mkozjak** [comment]
You need to configure a shell prompt.

**Comment by itsrajasekhar** [comment]
I tried configuring the shell prompt as ``` /Escape character is .*/ ``` event then it is not working

The redis telnet connection prompts as below

```
sekhar@home:~/raja$ telnet 127.0.0.1 8000
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
```

i tried the callback way but 'ready' event is never triggered for me. Please let me know if my understanding is wrong

**Comment by mkozjak** [comment]
redis-server doesn't emit any data back once tcp connection is established.
You would need to use ```shell``` like this:
```js
var telnet = require('telnet-client');
var connection = new telnet();

var params = { 
      host: '127.0.0.1',
      port: 6379
};

var cr = '\n'

connection.connect(params)

connection.shell().then(function(stream) {
    stream.on('data', (data) => console.log(data.toString()))

    stream.write('monitor' + cr) 
})
```

You basically have a nodejs' streams interface to use. Telnet can't help here much, unfortunately.

**Comment by itsrajasekhar** [comment]
Great it worked. Thanks a lot.
