### ISSUE TITLE
Can you add a sock option to connect like SSH2

### ISSUE THREAD

**Issue by kwesibrunee** [mkozjak/node-telnet-client#84]
Would it be possible to add a sock option to connect instead of creating a new tcp connection like in SSH2

here is the docs snippet from SSH2
sock - ReadableStream - A ReadableStream to use for communicating with the server instead of creating and using a new TCP connection (useful for connection hopping).

**Comment by mkozjak** [comment]
Thanks for the feature request. It is now implemented in version 0.14.0.
For further information check readme and also the tests.
