### ISSUE TITLE
Getting a connection refused

### ISSUE THREAD

**Issue by xanZ08** [mkozjak/node-telnet-client#85]
Hello,
What prompt value do I give, below is the screen shot of the system.
I get connection timeout.
![prompt](https://cloud.githubusercontent.com/assets/24983363/26265664/a0311ace-3ca7-11e7-8022-169d8e81f0a3.png)

**Comment by mkozjak** [comment]
Try setting the password prompt to "Enter password:"

**Comment by xanZ08** [comment]
Okay, where do I specify the password? in the password property?

**Comment by xanZ08** [comment]
var telnet = require('telnet-client');
var connection = new telnet();

var params = {
  host: '20.0.1.177',
  port: 7171,
  password:'adept',
  passwordPrompt:'Enter password:',
  timeout: 3500,
    debug:true
  // removeEcho: 4 
};


connection.on('ready', function(prompt) {
  connection.exec('adept\n\r', function(err, response) {
      if(err){
          console.log(err)
      }
      else{
    console.log(response);
      }
  });
});

connection.on('timeout', function() {
  console.log('socket timeout!')
  connection.end();
});
 
connection.on('close', function() {
  console.log('connection closed');
});
 

connection.on('error', function() {
  console.log('connection error');
});
connection.connect(params);

**Comment by mkozjak** [comment]
Yes, passwordPrompt.

**Comment by xanZ08** [comment]
I did not understand..so the passwordPrompt property be 'Enter password:' or 'adept' the password?

**Comment by xanZ08** [comment]
I am in a fix right now, and really need this to work , would really appreciate your help.

**Comment by xanZ08** [comment]
@mkozjak did you get a chance to look into it?

**Comment by mkozjak** [comment]
Use  'Enter password:'
