### ISSUE TITLE
Does not emitt the ready event

### ISSUE THREAD

**Issue by RagazziMoscow** [mkozjak/node-telnet-client#87]
When i use it to connect to Dlink router it does not emit the ready event. But the router responses successfuly. I see it in Wireshark analyze.

var telnet = require('telnet-client');
var connection = new telnet();

var params = {
  host: '192.168.1.1',
  port: 23,
  username: "admin",
  password: "admin",
  shellPrompt: '/ # ',
  timeout: 3500,
  debug: true
};

**Comment by mkozjak** [comment]
Your shellPrompt is most probably not '/ # '.
