### ISSUE TITLE
Telnet connection timeouts, but there is no debug print at all.

### ISSUE THREAD

**Issue by holywyvern** [mkozjak/node-telnet-client#90]
The connection always times out, it doesn't matter how long my timeout is, but using the regular telnet command in ubuntu works and doesn't take more than 400ms to connect.

Also when using debug: true never prints anything at all.

I'm using this piece of code:

```js
const telnet = new Telnet();

telnet.on('timeout', function() {
 console.log("timeout");
 telnet.end();
});
telnet.connect({
 host: 'XXX.XXX.XXX.XXX',
 username:    'user',
 password:    'pass',
 shellPrompt: 'DSLAM-PROMPT#',
 timeout:        15000,
 loginPrompt: /username[: ]*$/i,
 debug: true
}).then(prompt => {
     console.log("Connect: " + prompt)
});
```

Using the commands as usual works well:

```
telnet XXX.XXX.XXX.XXX 23
Trying XXX.XXX.XXX.XXX...
Connected to XXX.XXX.XXX.XXX.
Escape character is '^]'.
************************************************
Welcome to ZXAN product C320 of ZTE Corporation
************************************************
Username:
```
After utting my username and pressing enter:
```
Password:
```
And after pressing enter with my password:

```
DSLAM-PROMPT#
```
telnet-client version installed is 0.15.2, 
node version is v6.10.1, 
running on Ubuntu 14.04.5 LTS (GNU/Linux 3.13.0-24-generic x86_64)

**Comment by mkozjak** [comment]
Hi, @holywyvern. Please set passwordPrompt accordingly. The default one will not cover your case.

**Comment by mkozjak** [comment]
Hi, @holywyvern! Thanks for reporting. The debug flag is not working at the moment. I have a separate issue for that. Should be done soon.

I'll try reproducing the problem asap. Until then, you can try console.log'ing around in lib dir to find out where might be the problem.

**Comment by holywyvern** [comment]
I did an update first and check.
It didn't work.

So I tried to do the following:

Changed passwordPrompt to `passwordPrompt: /Password[: ]*$/i` and then to `passwordPrompt: "Password:"`

After that, I changed loginPrompt to `/Username[: ]*$/im`  and passwordPrompt to `/Password[: ]*$/im`.

It still doesn't work.

I am getting the IP using a database query, but then I printed the database row, and the telnet config at console and it displays the correct information

Finally I tried a silly final option wich was putting timeout at 1 hour. It didn't work either.

Is probably another type of bug in my code?
I'll write you the idea I'm using (but there is not even a "unhandled promise error" message:

```js

const telnet = new Telnet();
telnet.connect(options)
   .then(prompt => {
        console.log("Connected: ", prompt);
        const command = "show pon power attenuation gpon-onu_1/1/1:1"
        return telnet.exec(command);
   })
   .then(prompt => {
       console.log("Result: ", prompt);
   })
   .catch(error => {
       console.error(error);
   });
```
It doesn't even log the "Connected: " + prompt.

I also tried to use the callback style calls, but it didn't work either.

**Comment by mkozjak** [comment]
I'm currently unable to help without you lending me a tcpdump capture or your traffic. If you can, email me the sample and I'll try replicating the problem. Looking forward to help!

**Comment by holywyvern** [comment]
Co workers doen't enjoy using babel/webpack/gulp and we try to keep using LTS versions of node.
That aside, I'll try to do a tcpdump on the machine and see a difference between. 
If I find something strange I'll paste it here.
Thanks for the help.

**Comment by mkozjak** [comment]
Please, comment if needed and I'll reopen the issue!
