### ISSUE TITLE
Is there support for dynamic prompt?

### ISSUE THREAD

**Issue by RomanDoroshenko** [mkozjak/node-telnet-client#91]
While working with devices like Cisco, everything works just fine. I simply use bashPrompt: `/#/`, which works fine for:
```
Cisco_host#conf t
Enter configuration commands, one per line.  End with CNTL/Z.
Cisco_host(config)#
```
But, when I'm trying to work with Huawei devices, which change its prompt depending on config mode, I just can't get regexp: `/(>|])/`to work:
```
<Huawei_host>sys
Enter system view, return user view with Ctrl+Z.
[Huawei_host]
```

Nothing fashionable in my code. Simply:

```
...
const res = await connection.exec('sys`)
console.log(res)
```

P.S. I fairly new to js, so maybe there is something with my regexp.
I'm open to any suggestions. Thx in advance.

**Comment by mkozjak** [comment]
Hello, @RomanDoroshenko! First of all, thank you for choosing this library!

After you input `sys` in your telnet session, run next `exec` call with `shellPrompt` in options, which will set shellPrompt for the rest of that telnet session (tcp connection).

In example:

```js
const res = await connection.exec('sys')
const res2 = await connection.exec('my_next_command', { shellPrompt: '[Huawei_host]' }, ...
```

If you'd like to change the prompt again, just run `exec` with `shellPrompt` again once to set it.

**Comment by RomanDoroshenko** [comment]
**@mkozjak**, Thank you for reply. Already figured out that option, altough I would like initial regexp to work for both cases (I have dymanic command set based on info fetched from device), which would be more convinient. Is there no options to do that?

**Comment by mkozjak** [comment]
@RomanDoroshenko: Thanks for the request, actually!

I've pushed a new version, 0.15.4, which will resolve your problem. Once you set regex as your prompt, it will use that regex all the time until you set it to something else.
