### ISSUE TITLE
Login on Cisco with banners ending with prompt characters

### ISSUE THREAD

**Issue by unchained-za** [mkozjak/node-telnet-client#93]
I often have to login to Cisco hosts that use banners or MOTD banners that have lines ending with for instance '#'. As the hosts may login with either '>' or '#' prompt, I have to check for both, so in the case where there in a banner, the banner is accepted as a shell prompt the actual login fails. It requires reading all data from the host before checking for the login, password or shell prompt.

Can you possibly help me in resolving this issue?

**Comment by mkozjak** [comment]
Hi!

The only thing you could go for is a check for a socket timeout once you first try connecting with one of the prompts, ie. '#'.
Listen on the 'timeout' event and once it's hit, try another prompt.

There's no clear way to do it otherwise, currently.

**Comment by unchained-za** [comment]
Thanks, I seem to have it under control.
