### ISSUE TITLE
Not able to establish connection. always give error of 'connection timeout'.

### ISSUE THREAD

**Issue by vksdgreat** [mkozjak/node-telnet-client#94]
My requirement is to connect to Telnet client from node js.

I am using this code for connection

```
var Telnet = require('telnet-client')
var connection = new Telnet()

var params = {
  host: '127.0.0.1',
  port: 23,
  shellPrompt: '/ # ',
  timeout: 1500,
  // removeEcho: 4
}

connection.on('ready', function(prompt) {
connection.exec(cmd, function(err, response) {
console.log(response)
  })
})

connection.on('timeout', function() {
console.log('socket timeout!')
connection.end()
})

connection.on('close', function() {
  console.log('connection closed')
})

connection.connect(params)`
```
But it always return "socket timeout!" in console.

I also tried by adding 'username' and 'password' details in params

```
`var params = {
        host: '127.0.0.1',
        port: 23,
        shellPrompt: '/ #',
        loginPrompt: 'Username: ',
        passwordPrompt: 'Password: ',
        username: 'vinit',
        password: 'vinit123',
        initialLFCR: true,
        timeout: 1500,
        // removeEcho: 4
}`
```
but still facing the same issue. In some links i found people saying that shellPrompt value is incorrect then what should be the value of shellPrompt. actually i am completely new to this topic so don't have much idea about it.

I checked the credentials are ok. but not able to connect through this module.

Any help will be appreciated. Thanks in advance.

**Comment by mkozjak** [comment]
Connect to your telnet server with `telnet` if you're on Unix or whatever else if you're on Windows.
Then check what's the prompt looking like. That's the one you will need to use for `shellPrompt`.

**Comment by vksdgreat** [comment]
@mkozjak  can you please guide me how to find value of `shellPrompt` for my server. 

by searching about it on google i found that i can get it by this command `echo $PS1`. When i run this command i got this response -  `\[\e]0;\u@\h: \w\a\]${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$`

so should i pass this value in shellPrompt?

**Comment by mkozjak** [comment]
@vksdgreat: No, you just use the one from the prompt you got when you manually connected to your telnet server with `telnet`. In example `/ # ` for busybox.

**Comment by vksdgreat** [comment]
I got this `radius login:` after typing telnet XXX.XXX.XXX.XXX does that mean my `shellPrompt` is `radius  ` and `loginPrompt` is `login:`

**Comment by mkozjak** [comment]
Your `loginPrompt` is then `radius login:`.
You'll see what the `shellPrompt` will be after you login.

**Comment by vksdgreat** [comment]
`vinit@radius:~$ ` this is what i am getting after login to telnet server.

**Comment by mkozjak** [comment]
Then `shellPrompt` is `vinit@radius:~$`

**Comment by vksdgreat** [comment]
Thanks!!.. It is working now. :)
