### ISSUE TITLE
"data" event doesn't seem to be firing 

### ISSUE THREAD

**Issue by RyanDelap** [mkozjak/node-telnet-client#95]
I am trying to intercept data as the socket is recieving it using this telnet library, however it seems that the data event isn't firing. Trying the code from #43. 

```javascript
var Telnet = require('telnet-client')
var connection = new Telnet()

var params = {
  host: 'route-server.bb.pipex.net',
  port: 23,
  shellPrompt: '>',
  timeout: 30000,
  execTimeout: 30000
}

connection.on('ready', function(prompt) {
  connection.exec("ping google.com", function(err, response) {
    console.log(response)
  })
})

connection.on('timeout', function() {
  console.log('socket timeout!')
  connection.end()
})

connection.on('data', function(data) {
    console.log("Recieved Data: ", data);
})

connection.on('close', function() {
  console.log('connection closed')
})

connection.connect(params)
```

I've tried with several different telnet servers. I'm a novice to JS so I'm probably doing something wrong. 

Thanks.

**Comment by RyanDelap** [comment]
I have created PR request #96 addressing this issue.

**Comment by mkozjak** [comment]
@RyanDelap: Use the `initialLFCR` option when connecting! Your server seems to need it.

**Comment by RyanDelap** [comment]
@mkozjak 
Thanks for the response, however adding this option to the regular code seemed to break the response. I now recieve no output of any kind.

``` 
var Telnet = require('telnet-client')
var connection = new Telnet()

var params = {
  host: 'route-server.bb.pipex.net',
  port: 23,
  shellPrompt: '>',
  timeout: 120000,
  execTimeout: 25000,
  initialLFCR: true
}

connection.on('ready', function(prompt) {
  connection.exec("ping google.com", function(err, response) {
    console.log(response)
  })
})

connection.on('timeout', function() {
  console.log('socket timeout!')
  connection.end()
})

connection.on('close', function() {
  console.log('connection closed')
})

connection.connect(params)
```

**Comment by mkozjak** [comment]
@RyanDelap Server is acting strange... It waits for <return> to be pushed and then returns a first prompt, after which the library sends the command, but for some reason the server throws back another prompt at once, and that's why you don't get any responses.

Use a timeout like this for a workaround:
```
setTimeout(() => {
    connection.exec("ping google.com", function(err, response) {
        ...
    })
}, 10)
```
