### ISSUE TITLE
echoLines in exec

### ISSUE THREAD

**Issue by Pulkownikfgs** [mkozjak/node-telnet-client#97]
https://github.com/mkozjak/node-telnet-client/blob/0cfd9a685faeb13af04891a15a3f2ac1e274c23a/lib/index.js#L125

When echoLines is set to 0 in params for exec(), it'll be omitted in favor of previously set value.

Suggested fix:
`this.echoLines = (typeof opts.echoLines !== 'undefined' ? opts.echoLines : this.echoLines)`

**Comment by mkozjak** [comment]
@Pulkownikfgs Thanks for the suggestion! Mind doing a PR, so you end up as a contributor, maybe?
