### ISSUE TITLE
I gona build a cli tool for this. But...

### ISSUE THREAD

**Issue by axetroy** [mkozjak/node-telnet-client#99]
There still a lot of Bugs. :joy:

I have write the code follow the Example, and try again and again.

I think it is not time yet for using.

anyway, I wish it will be better

**Comment by mkozjak** [comment]
Thank you for your thorough review of my library and an extensive explanation of its problems throughout your usecase. 

With all due respect, I believe you will not be able to create such a tool. Maybe try using another library or even another language. Or turn off your computer and quit your project altogether. For the better of all mankind!

Regards.
